# Problem 1 

In [2]:
import numpy as np
a=np.array([8,3,2,9,0])
print(np.sort(a,axis=0))

[0 2 3 8 9]


# Problem 2

In [44]:
import numpy as np
print(np.array([10,15,30,45,60]))
print(np.arange(5,15))
print(np.arange(50,100,5))
print(np.zeros(10))
print(np.ones(10))
print(np.linspace(0,100,5))
print(np.random.randint(10,30,5))
print(np.random.normal(-1,1,(5,2)))
a=np.random.randint(10,50,size=[3,5])
print(a)
print(a.shape[0]+a.shape[1])
b=a.flatten()
b.sort()
print(b)
print(b[0])
print(b[14])
print((b[0]+b[14])/2)
print(np.argmax(b))
c=np.arange(10,20)
print(c)
print(c[0])
print(c[1])
print(c[2])
d=c[::-1]
print(d)
a=np.random.randint(10,50,size=[3,5])
print(a)
print(a[0])
print(a[1,2])
print(a[(0,1,2),0])
print(a**2)
d=np.random.randint(-50,+50,size=(5,5))
print(d)
e=(d>0)&(d%2==0)
d[e]


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[29 15 26 27 14]
[[-1.31055924 -0.16282068]
 [-3.00099477 -2.23360015]
 [-0.58877511 -1.95207453]
 [-1.36290878 -0.86928929]
 [-1.49076183  0.32476438]]
[[18 18 12 11 42]
 [38 17 28 31 27]
 [25 27 34 38 40]]
8
[11 12 17 18 18 25 27 27 28 31 34 38 38 40 42]
11
42
26.5
14
[10 11 12 13 14 15 16 17 18 19]
10
11
12
[19 18 17 16 15 14 13 12 11 10]
[[38 29 38 41 24]
 [27 44 19 49 42]
 [16 21 14 36 40]]
[38 29 38 41 24]
19
[38 27 16]
[[1444  841 1444 1681  576]
 [ 729 1936  361 2401 1764]
 [ 256  441  196 1296 1600]]
[[-49   8   8  34   2]
 [ 14 -22  10   9 -44]
 [ 32  -5 -34 -11 -50]
 [ 26  39  -6 -38 -18]
 [ 14  12  29  -7 -19]]


array([ 8,  8, 34,  2, 14, 10, 32, 26, 14, 12])