### Soru 1 

Yazılımcıların bir dili öğrenmeye başladığında ilk yapacakları şey ekrana "Hello World" yazdırmaktır. Python'da da aynı şeyi yapalım.Bir yazılımcı aşağıdaki kodu yazarken hata yapıyor. Bunu düzelterek çalışan bir kod yazalım.


In [1]:
print ("Hello World")

Hello World


In [1]:
print('hello world')

hello world


In [2]:
print("""hello world""")

hello world


In [3]:
"hello world"

'hello world'

In [ ]:
tek satırlık olduğu için problem yok

In [4]:
"pyhton öğreniyorum"
"yetgen ile python öğreniyorum"

'yetgen ile python öğreniyorum'

sadece son satırı veriyor ama print fonksiyonu ile her iki satırı yazdırabilirsin.

sep parametresi print fonksiyonu ile kullanılır öğeler arasına koyulacak parametreyi gösterir.

In [8]:
print("hello","world",sep=", ")

hello, world


In [10]:
print("python","öğreniyorum")

python öğreniyorum


sep parametresi konulmazsa otomatik varmış gibi kabul edip çalıştırıyor

In [11]:
print("ankara","istanbul","izmir", sep="/")

ankara/istanbul/izmir


end parametresi de sep parametrei gibi görünmese bile oradadır, parametrelerin sonuna neyin geleceğini belirler.

In [12]:
print("yetgen dikeyine hoş geldiniz", end=".")

yetgen dikeyine hoş geldiniz.

In [13]:
print("python'a ilk adımı attım",end="")

python'a ilk adımı attım

end parametresini içi boş bir şekilde yazdık, cümlenin sonuna hiçbir şey gelmedi. end paramatresini biz yazmasak da parametre hep o şkilde oradadır.

In [14]:
print('python'a hoş geldiniz)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2931348254.py, line 1)

hata veriyor çünkü baştakini çift tırnak yapmalı ve cümle sonuna da eklemeliyiz.

In [15]:
print("python'a hoş geldiniz")

python'a hoş geldiniz


print fonksiyonunu kullanırken hem tırnak hem de parantez kelime yazımları için zorunludur. sayı kullanımları farklıdır, örnek;

In [16]:
print(3.14)

3.14


yorum satırları
-python programlama dilinde tek satır halinde açıklama satırı eklemek için # işsareti, çoklu yorum satırı için üç tane tek tırnak kullanılır.
-satırın başı ve sonu arasındaki herhangi bir metin veya kod python tarafıdan yok sayılır ve çalıştırılmaz.
-kodu inceleyen başka yazılımcılara ipucu vermek için kullanılır.

In [19]:
#tekli yorum satırı
print("ocak ayında hava çok soğuk") #print() fonksiyonu ekrana baskı yapmayı sağlar.

ocak ayında hava çok soğuk


dneme.py dosyasında örnek yaptım, kontrol edebilirsin hatırlamak için.

üç tane tek tırnak bırakmak için shift+2

değişkenler
değişkenleri bir verinin değerini saklamayı sağlar.

In [1]:
print("yetgen jump")
print("yetgen jump")
print("yetgen jump")

yetgen jump
yetgen jump
yetgen jump


In [4]:
yetgen="hazal"
print(yetgen)
print(yetgen)
print(yetgen)


hazal
hazal
hazal


değişken tanımlama kuralları
-değişken adlandırmada sayılar, harfler ya da alt çizgi kullanılabilir ama değişken isimlendirmeleri alt çizgi ya da harfle başlar.
-sadece ingilizce karakterler kullanılır.
-büyük küçük harf duyarlıdır.
-değişken adları ne çok kısa ne de çok uzun olmalıdır. aynı zamanda kodu okuyan kişinin değişkenin niçin kullanıldığını anlaması gerekir.
-değişken isimlendirirlen boşluk kullanmıyoruz.

camsel case adlandrıma, isimlendirme türünde ilk harf küçük harf ile başlar ve sonraki her yeni sözcüğün ilk harfi büyük olmalıdır.

In [6]:
isimSoyisim="hazal kocaoğlu"
print(isimSoyisim)

hazal kocaoğlu


snake case adlandırma, isimlendirme türünde her yeni sözcüğün arası alt çizgi ile ayrılır ve her kelime küçük harf ile başlar.

In [7]:
isim_soyisim="hazal kocaoğlu"
print(isim_soyisim)

hazal kocaoğlu


büyük küçük harf duyarlılığı nedir?

In [9]:
isim="a"
print(isim)
İsim="b"
print(İsim)

a
b


In [1]:
1hazal="kocaoğlu"
print(1hazal)

SyntaxError: invalid decimal literal (635794674.py, line 1)

hata verdi çünkü sayıyla başlayamayız.

In [3]:
hazal="kocaoğlu"
print(hazal)
_hazal="kocaoğlu"
print(_hazal)

kocaoğlu
kocaoğlu


In [4]:
sayi=5
print(sayi)

5


türkçe karakter kullanmıyoruz.

type() komutu
-bir değişkenin integer, float, string ya da boolean olup olmadığını verir, yani veri tipini verir.
-yalnızca type yazarsak tek bir satır için çalışır, birden fazla satır için çalışmasını istersek print ile yazmalıyız.

In [15]:
print(type("hazal"))

<class 'str'>


In [16]:
type(1)

int

In [18]:
type(True)

bool

küçük harf true yazınca hata verdi

In [19]:
type(3.14)

float

In [21]:
print(type("hazal"))
print(type(1))
print(type(True))
print(type(3.14))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


integer

In [22]:
print(10)

10


In [23]:
print(type(10))

<class 'int'>


float
-ondalıklı sayıları ifade eder.
-python iki rakamı birbirine böldüğü zaman gerçek sonuca ulaşmak için float değer döndürür.

In [24]:
pi=3.14
print(pi)
print(type(pi))

3.14
<class 'float'>


matematiksel işlemler
+toplama
-çıkarma
*çarpma
/bölme
**üs alma
%mod alma
//tam bölme

In [28]:
a=3
b=4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

7
-1
12
0.75
81


string
-metinsel ifadelerdir.
-metinsel iafdederin tek, çift ya da üç tırnak arasına yazılması gerekir.
-metinsel ifadelerde eğer tek tırnak ile başlamış ise tek tırnak ile devam edilmesi gerekmektedir.
-metinsel ifadelerin index ile ulaşma imkanı sağlar. yazılımda index 0'dan başlar. mesela "merhaba dünya" metninin ikinci indexinde r harfi vardır.

In [29]:
degisken="merhaba python"
print(degisken)

merhaba python


In [32]:
degisken='ben hazal'
print(degisken)

ben hazal


bir string'in(karakter dizisinin) herhangi bir karakterine ulaşmak istediğimizde indexing(elemanlara erişme) işlemini kullanırız.
string'ler index'lenmeye 0'dan başlar ve "[]"(köşeli parantez) ile gösterilir.
örnek string: yetgen
1.harf(0. index):y
2.harf(1. index):e
3.harf(2. index):t
4.harf(3. index):g
5.harf(4. index):e
6.harf(5. index):n


[] option+8
{} option+7

In [42]:
print(degisken[0])
print(degisken[1])
print(degisken[2])
print(degisken[3])
print(degisken[4])
print(degisken[5])
print(degisken[6])
print(degisken[7])
print(degisken[8])
print(degisken[-1])
print(degisken[-2])
print(degisken[-3])
print(degisken[-4])
print(degisken[-5])
print(degisken[-6])
print(degisken[-7])
print(degisken[-8])
print(degisken[-9])

b
e
n
 
h
a
z
a
l
l
a
z
a
h
 
n
e
b


In [44]:
isim="hazal"
soyisim="kocaoğlu"
print(isim+" "+soyisim)

hazal kocaoğlu


In [45]:
isim="hazal"
soyisim="kocaoğlu"
yas=20
print(isim+" "+soyisim+" "+yas)

TypeError: can only concatenate str (not "int") to str

error veriyor çünkü integer ile stringi bir arada kullanamayız, virgül koyarak deneyelim.

In [47]:
print(isim,"",soyisim,"",yas)

hazal  kocaoğlu  20


In [50]:
print(f"{isim} {soyisim} {yas}")

hazal kocaoğlu 20


boolean
-sadece true ya da false değerini döndürür.

In [51]:
hazaloradami=True
print(hazaloradami)
print(type(hazaloradami))

True
<class 'bool'>


input
-kullanıcıdan veri almamızı sağlar 
-input ile veri alırken string gibi davranır bu yüzden input alırken sayı alacaksan int ya da float kullan.

In [59]:
isim=input("isim giriniz:")
print(f"merhaba {isim}")
print("merhaba",isim)
print("merhaba "+isim)

merhaba hazal
merhaba hazal
merhaba hazal


In [60]:
sayi1=input("birinci sayıyı giriniz:")
sayi2=input("ikinci sayıyı giriniz:")
print(sayi1+sayi2)

56


bıurada birinci sayıyı 5, ikinci sayıyı 6 girdim ve sonuş 56 çıktı. sonucun  bu şekilde yanlış çıkmasının sebebi string toplama yapmış olmamız. bunu düzeltmek için de float veya integer girmeliyiz.

In [61]:
sayi1=int(input("birinci sayıyı giriniz:"))
sayi2=int(input("ikinci sayıyı giriniz:"))
print(sayi1+sayi2)

11


sonuç 5+6 dan 11 olarak doğru çıktı.

In [62]:
print(f"{sayi1}+{sayi2}={sayi1+sayi2}")

5+6=11


format kullanımı

In [4]:
pi=3.14
r=5
h=10
cylinder=pi*r**2*h
cone=1/3*pi*r**2*h
print("{} cm yarıçaplı ve {} cm yüksekliğindeki silindirin hacmi {} cm^3 ve koninin hacmi {} cm^3'tür.". format(r,h,cylinder,cone))

5 cm yarıçaplı ve 10 cm yüksekliğindeki silindirin hacmi 785.0 cm^3 ve koninin hacmi 261.66666666666663 cm^3'tür.


round kullanımı
round fonksiyounu bir sayıyı belirli bir hassasiyete göre yuvarlamak için kullanılır.
yani sayıları anlamlı sayıya çeviriyoruz.

In [5]:
print("bahşiş hesaplayıcıya hoş geldiniz!")
hesap=float(input("hesap ne kadar geldi?"))
bahsis=int(input("yüzde kaç başiş vermek istersin?"))
kisisayisi=int(input("hesabı kaç kişi ödeyecek?"))
yuzdebahsis=bahsis/100
toplambahsismiktari=hesap*yuzdebahsis
toplamhesap=hesap+toplambahsismiktari
kisibasihesap=toplamhesap/kisisayisi
sonmiktar=round(kisibasihesap,2)
print("kisi başı ödenecek hesap:₺", sonmiktar)

bahşiş hesaplayıcıya hoş geldiniz!
kisi başı ödenecek hesap:₺ 18.67


round fonksiyonu burada virgülden sonra iki basamak yazmamızı sağladı

karşılaştırma operatörleri
* = atama operatörüdür.
* == iki değerin birbirine eşit olup olmadığını kontrol eder. Eşitse True eşit değilse False değerini döndürür.
* != eşit değil mi? cevap eşit değilse True eşitse False değerini döndürür.
* > büyüktür
* < küçüktür
* >= büyük eşit 
* <= küçük eşit

In [10]:
a, b, c, d= 5, 5, 10, 4
print(a==b)
print(a==c)
username="admin"
password="12345"
print("berkcan"==username)
print(a!=b)
print(a!=c)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

True
False
False
False
True
False
False
True
True


% tam bölünüp bölünmediğini sorgular

In [11]:
x=4
x%2

0

sonucun sıfır çıkması tam bölündüğünü gösterir.

mantıksal operatörler
and operatörü
-true and true= true
-true and false= false
-false and true= false
-false and false= false
-eğer her iki durum da doğruysa true diğer durumlarda false değerini döndürür.

or operatörü
-true or true= true
-true or false= true
-false or true= true
-false or false= false
-yalnızca iki durumun yanlış olduğu durumlada false diğer bütün durumlarda true değerini verir.

not operatörü
-true değerini false değerine, false değerini true değerine döndürür.

In [14]:
x=int(input("bir sayı giriniz:"))
print(x>5 and x<100)

True


In [16]:
y=5
hazal= True
print(y>0 and hazal==True)

True


In [18]:
x=int(input("bir sayı giriniz:"))
print(x>0 or x%2==0)

True


In [19]:
print(3>1 and 3>2)

True


In [22]:
print(3>1 or 3>2)

True


In [23]:
print(not(True))

False


karar yapıları
*eğer if bloğu doğruysa diğer durumlara bakılmaz ve if bloğu altındaki kodlar çalışır.
*else yapısının kullanılması zorunlu değildir olsa da olur olmasa da olur.
*elif yapısının kullanılması zorunlu değildir olsa da olur olmasa da olur.
*else yapısı if ve varsa elif yapısının false olduğu durumda ikinci nihai durum olarak çalışır.
*elif yapısını birden çok farklı koşullardan doğacak durumların kontrolünü sağlamak için kullanırız.

if koşul:
    # koşul doğruysa çalışacak kodlar
elif koşul2:
    # koşul2 doğruysa çalışacak kodlar
else:
    # koşul1 ve koşul2 yanlışsa çalışacak kodlar

*** if yazdıktan sonra kodu yazmadan önce 4 tane boşluk bırakmalıyız.

In [1]:
if 3>1:
    print("if bloğu çalıştı")
print("program sonlandı")

if bloğu çalıştı
program sonlandı


In [2]:
if 0>1:
    print("if bloğu çalıştı")
print("program sonlandı")
    

program sonlandı


In [3]:
sayi1=int(input("1. sayıyı giriniz:"))
sayi2=int(input("2. sayıyı girimiz:"))
if sayi1>sayi2:
    print("1. sayı 2. sayıdan büyüktür.")
elif sayi1==sayi2:
    print("sayılar birbirine eşittir. ")
else:
    print("2. sayı 1. sayıdan büyüktür.")


1. sayı 2. sayıdan büyüktür.


In [5]:
sayi1=int(input("1. sayıyı giriniz:"))
sayi2=int(input("2. sayıyı girimiz:"))
if sayi1>sayi2:
    print("1. sayı 2. sayıdan büyüktür.")
elif sayi1==sayi2:
    print("sayılar birbirine eşittir. ")
elif sayi1<sayi2:
    print("2. sayı 1. sayıdan büyüktür.")


2. sayı 1. sayıdan büyüktür.


In [9]:
superkahraman=input("bie süper kahraman giriniz:")
if superkahraman=="batman":
    print("batmani seçtiniz.")
elif superkahraman=="superman":
    print("supermani seçtiniz.")
elif superkahraman=="ıronman":
    print("ıronmani seçtiniz.")
else:
    print("böyle bir süper kahramanımız yok.")

böyle bir süper kahramanımız yok.


In [18]:
a=10
b=20
c=30
if a>b and b>c:
    print(f"{a} sayısı {b} sayısından büyüktür ve {b} sayısı {c} sayısından büyüktür.")
if a<b and b<c:
    print(f"{a} sayısı {b} sayısından küçüktür ve {b} sayısı {c} sayısından küçüktür.")
else:
    print("bu koşullar tutmadı.")

10 sayısı 20 sayısından küçüktür ve 20 sayısı 30 sayısından küçüktür.


In [20]:
yetgenmezunu= True
if yetgenmezunu:
    print("yetgen mezunusunuz.")
else:
    print("yetgen mezunu değilsiniz.")

yetgen mezunusunuz.


In [21]:
sayi3=10
sayi4=20
if sayi3>5:
    print("3. sayı 5'ten büyüktür.")
    if sayi4>10:
        print("4. sayı 10'dan büyüktür.")
    else:
        print("ikinci else")
else:
    print("birinci else")

3. sayı 5'ten büyüktür.
4. sayı 10'dan büyüktür.


In [31]:
isim="hazal"
if "kocaoğlu" in isim:
    print("var")
else:
    print("yok")

yok


bir sayının çift olup olmadığını ikiye bölümünden kalanı(mod 2) kontrol ederek bulabiliriz.
eğer, sayının iki ile bölümü 0 ise (mod 2 = 0), sayı çifttir.
eğer, sayının iki ile bölümü 0 değil ise ( mod 2!= 0), sayı tektir.

In [32]:
sayi=int(input("bir sayı giriniz:"))
if sayi%2==0:
    print(f"{sayi} sayısı çifttir.")
else:
    print(f"{sayi} sayısı tektir.")
    

4 sayısı çifttir.


in operatörü
-belirtilen bir değerin dizi, metin liste veya demet givi bir dizinin öğesi olup olmadığını kontrol eder. True ya da False değeri döndürür.

In [35]:
string="yetgen"
"p" in string
"y" in string

True

döngüler
-döngüler temel olarak verilen koşullar karşılanana kadar tekrar eden bir süreçtir.
-döngünün koşulu her zaman doğruysa döngü sonsuza kadar devam eder. buna sonsuz döngü denir. bu tür döngülere genellikle while döngüsünde rastlarız.
-eğer bir döngünün koşulu baştan yanlışsa döngü çalışmaz. buna sıfır açma döngüsü denir.

for döngüsü
-for döngüsü listelerin, demetlerin, stringlerin ve hatta sözlüklerin üzerinde dolaşmamızı sağlar. yapısı şu şekildedir:
for eleman in veriyapısı:
    yapılacak işlemler

In [1]:
liste=[1,2,3,4,5]
for i in liste:
    print(i)

1
2
3
4
5


In [2]:
for i in liste:
    print(i**2)

1
4
9
16
25


In [3]:
string= "yetgen jump"
for string1 in string:
    print(string1)

y
e
t
g
e
n
 
j
u
m
p


In [4]:
sayilar= "12345"
for x in sayilar:
    print(int(i)*int(i))

25
25
25
25
25


In [5]:
sayilar= "12345"
for x in sayilar:
    print(int(x)*int(x))

1
4
9
16
25


while döngüsü
-while döngüleri belli bir koşul sağlandığı sürece bloğundaki işlemleri gerçekleştirmeye devam eder.while döngülerinin sona ermesi için koşul durumunun bir süre sonra False olması gerekir. yapısı şu şekildedir:
while koşul:
    yapılacak işlemler 

In [22]:
sum=0
i=1
while i<11:
    sum+=i #sum=sum+i
    i+=1
print("toplam:", sum)


toplam: 55


range() fonksiyonu
-range(başlangıç, bitiş, artış miktarı) şeklinde kullanır.

In [9]:
print(range(1,10,2))

range(1, 10, 2)


In [10]:
for x in range (1,10,2):
    print(x)

1
3
5
7
9


In [11]:
for x in range(5):
    print(x)

0
1
2
3
4


In [14]:
for x in range(0,101,10):
    print(x)

0
10
20
30
40
50
60
70
80
90
100


break
-break ifadesi döngüyü sonlandırır.
continue
-continue ifadesi döngünün sonraki adımına geçer.

In [16]:
i=0 
while i<10:
    if(i==5):
        break
    else:
        print(i)
        i+=1

0
1
2
3
4


In [2]:
while True:
    print(" uygulamadan çıkmak için q tuşuna basınız.")
    yas=input("yaş:")
    if(yas=="q"):
        break
    else:
        print("yaşınız:", yas)

 uygulamadan çıkmak için q tuşuna basınız.
yaşınız: 25
 uygulamadan çıkmak için q tuşuna basınız.
yaşınız: 20
 uygulamadan çıkmak için q tuşuna basınız.


In [21]:
for i in range(7):
    if i==5:
        continue
print(i)

6


Kullanıcıdan aldığınız bir sayının "Armstrong" sayısı olup olmadığını bulmaya çalışın.
Örnek olarak, Bir sayı eğer 4 basamaklı ise ve oluşturan rakamlardan herbirinin 4. kuvvetinin toplamı( 3 basamaklı sayılar için 3.kuvveti ) o sayıya eşitse bu sayıya "Armstrong" sayısı denir.

Örnek olarak : 1634 = 1^4 + 6^4 + 3^4 + 4^4

In [ ]:
def isanarmstrongnumber(number):
    digits=[int(d)for d in str(number)]
    numberofdigits=len(digits)
    sumofpowers=sum([digit**numberofdigits for digit in digits])

    return sumofpowers==number
number=int(input("enter a number:"))
if isanarmstrongnumber(number):
    print(f"{number} is an armstrong number.")
else:
    print(f"{number} is not an armstrong number.")

Kullanıcıdan aldığınız bir sayının mükemmel olup olmadığını bulmaya çalışın.
Bir sayının kendi hariç bölenlerinin toplamı kendine eşitse bu sayıya "mükemmel sayı" denir. Örnek olarak, 6 mükemmel bir sayıdır. (1 + 2 + 3 = 6)

In [ ]:
number=int(input("enter a number"))
def isaperfectnumber(number):

    sumofdivisors=0

    for i in range(1, number//2+1):
        if number%i==0:
            sumofdivisors+=i

    return sumofdivisors==number
if isaperfectnumber(number):
    print(f"{number} is a perfect number")
else:
    print(f"{number} is not a perfect number")

YetGen Core Python mezunu bir öğretmenimiz öğrencilerine 1'den 10'a kadar sayılarla çarpım tablosunu öğretirken Python'dan destek almak istiyor. Bu konuda öğretmenimize yardımcı olmak ister misin?

İpucu: İç içe 2 tane for döngüsü kullanın. 

Aynı zamanda sayıları range() fonksiyonunu kullanarak elde edin.

In [ ]:
for x in range(1,11):
    print(x,"time table")
    for y in range(1,11):
        print(x,"x",y,"=",x*y)

listeler
-[] içerisinde tutulurlar.
-indexleme, veri güncelleme, silme, veri ekleme gibi işlemler yapılabilir.
-iç içe listeleme işlemi yapılabilir.

In [2]:
liderler=["ahmet", "eslem", "berkcan","çağla"]
print(liderler)
print(liderler[0])
print(liderler[-1])

['ahmet', 'eslem', 'berkcan', 'çağla']
ahmet
çağla


liste metodları
-append():listenin souna eleman ekler.
-remove():listenin içindeki elemanı siler.

In [3]:
liderler.append("emirhan")
print(liderler)
liderler.remove("berkcan")
print(liderler)

['ahmet', 'eslem', 'berkcan', 'çağla', 'emirhan']
['ahmet', 'eslem', 'çağla', 'emirhan']


In [4]:
liderler[5]="berkcan"
print(liderler)

IndexError: list assignment index out of range

hata veriyor çünkü beş tane elemanımız yok.

In [5]:
liderler[2]="berkcan"
print(liderler)

['ahmet', 'eslem', 'berkcan', 'emirhan']


len(): listenin uzunluğunu verir.

In [6]:
print(len(liderler))

4


clear()=listenin içindeki elemanları siler.

In [7]:
liderler.clear()
liderler

[]

index():
-listedeki elemanın indexini verir.
-aranan veriyi bulduğunda durur. diğer verilerde aynı veri varsa getirmez.

In [8]:
sehirler=list(("ankara","istanbul","izmir"))
print(sehirler)

['ankara', 'istanbul', 'izmir']


In [9]:
print("ankara'nın indexi:", sehirler.index("ankara"))

ankara'nın indexi: 0


In [11]:
print("ankara'nın indexi:"+ str(sehirler.index("ankara")))

ankara'nın indexi:0


In [12]:
print("ankara'nın indexi:"+ str(sehirler.index("antalya")))

ValueError: 'antalya' is not in list

hata verdi çünkü antalya listede değil.

In [14]:
sehirler=list(("ankara","ankara","izmir"))
print(sehirler)
print("ankara'nın indexi:", sehirler.index("ankara"))

['ankara', 'ankara', 'izmir']
ankara'nın indexi: 0


ankara'yı iki kere yazmış olmamıza rağmen sıfır dedi, çünkü krallara da yazdığımız gibi ilkini görüyor ve diğerlerini görmüyor.

pop():listedeki elemanı siler.
-index verilmezse son elemanı siler.
-index verilirse verilen indexi siler.

In [23]:
sehirler=list(("ankara","istanbul","izmir"))
sehirler.pop()

'ankara'

In [30]:
sehirler=list(("ankara","istanbul","izmir"))
sehirler.pop(0)

'ankara'

In [34]:
sehirler=list(("ankara","istanbul","izmir"))
sehirler

['ankara', 'istanbul', 'izmir']

insert():istenilen indexe eleman ekler.

In [35]:
sehirler.insert(0,"adana")
sehirler.insert(1,"istanbul")
sehirler.insert(2,"izmir")
print(sehirler)

['adana', 'istanbul', 'izmir', 'ankara', 'istanbul', 'izmir']


reverse():listeyi ters çevirir.

In [36]:
sehirler.reverse()
print(sehirler)

['izmir', 'istanbul', 'ankara', 'izmir', 'istanbul', 'adana']


sort():listeyi küçükten büyüğe sıralar.

In [37]:
sehirler.sort()
print(sehirler)

['adana', 'ankara', 'istanbul', 'istanbul', 'izmir', 'izmir']


liste toplama
-iki listeyi birleştirir.

In [38]:
liste1=["berkcan","ahmet"]
liste2=["enes","çağla"]
print(liste1+liste2)

['berkcan', 'ahmet', 'enes', 'çağla']


In [39]:
nestedlist=[1,5,"berkcan",4,[6,"z"]]
print(nestedlist[0])
print(nestedlist[1])
print(nestedlist[2])
print(nestedlist[3])
print(nestedlist[4][0])
print(nestedlist[4][1])

1
5
berkcan
4
6
z


tuple(demet)
-tuple listelere benzerdir.
-tuple ile liste arasındaki en önemli fark tuple elemanlarının değiştirilemez, liste elemanlarının değiştirilebilir olmasıdır.
-performanslı bir data sağlar.
-() içerisinde tanımlanabilir.
-iç içe tuple oluşturulabilir.
-liste içerisinde tuple, tuple içerisinde tuple tanımlamak mümkündür.
-bir kere tanımlandıktan sonra değiştirilemezler, yalnızca okunurlar.
-tek elemansa tuple olduğunu belirtmek için bir virgül koyulmalıdır.

In [40]:
tuplelist=(2,4,6,"ankara",[2,4,6])
print(type(tuplelist))

<class 'tuple'>


In [41]:
print(tuplelist)

(2, 4, 6, 'ankara', [2, 4, 6])


In [42]:
print(len(tuplelist))

5


In [43]:
tuplelist[0]=5
print(tuplelist)

TypeError: 'tuple' object does not support item assignment

hata verdi çünkü tuple'de liste gibi yer değiştiremeyiz.

In [44]:
print(tuplelist[-2])

ankara


In [45]:
print(tuplelist[1:2])

(4,)


bunun anlamı 1'den 2'ye kadar olan elemanları yazdır demektir.

set
-listelere benzer.
-en önemli özelliği indexsiz ve sırasız elemanlardan oluşmasıdır.
-veri tekrarı söz konusu değildir. tüm elemanlar eşsizdir.
-{} içerisinde tanımlanır.
-çok hızlı bir veri tipidir.

In [46]:
liderler={"berkcan","ahmet"}
print(liderler)
print(type(liderler))

{'berkcan', 'ahmet'}
<class 'set'>


In [47]:
liderler={"berkcan","ahmet","ahmet"}
print(liderler)
print(type(liderler))

{'berkcan', 'ahmet'}
<class 'set'>


ahmet'i iki kere yazdık ama tek olarak algıladı.

In [48]:
liderler={"berkcan","ahmet","ahmet"}
print(liderler[0])

TypeError: 'set' object is not subscriptable

set'ler indexlenemez bu nedenle hata veriyor.

In [49]:
for lider in liderler:
    print(lider)

berkcan
ahmet


In [50]:
print("berkcan" in liderler)

True


set metodları
-add():sete eleman ekler.
-remove():setten eleman siler.
-clear():setin içerisindeki elemanları siler.
-pop():setin son elemanını siler.
-update():sete eleman ekler.
-union():iki seti birleştirir.
-intersection():iki setin kesişimini alır.
-difference():iki setin farkını alır.

In [51]:
liderler.add("enes")
print(liderler)

{'enes', 'berkcan', 'ahmet'}


In [58]:
liderler={"berkcan","ahmet","ahmet"}
liderler.update(["emirhan","eslem","çağla"])
print(liderler)

{'eslem', 'berkcan', 'çağla', 'ahmet', 'emirhan'}


In [59]:
liderler={"berkcan","ahmet","ahmet"}
liderler.remove("berkcan")
print(liderler)

{'ahmet'}


In [61]:
liderler={"berkcan","ahmet","eslem"}
liderler.pop()
print(liderler)

{'berkcan', 'ahmet'}


In [62]:
set1={1,2,3}
set2={2,3,4}
set1.union(set2)

{1, 2, 3, 4}

In [63]:
set1.intersection(set2)

{2, 3}

In [64]:
set1.difference(set2)

{1}

In [65]:
set2.difference(set1)

{4}

In [66]:
set1.clear()
set1

set()

dictionary
-sınırsız veri tutar.
-günlük hayatta olan sözlükler gibi düşünebiliriz.
-{} arasında tanımlanır.
-key:anahtar bir bilgiye ulaşmak için kullanılır.
-value:değer
-key value için örnek verecek olursak:{06:"ankara"} 06 key ankara value
-dict("") şeklinde de sözlük tanımlayabiliriz.

In [67]:
sozluk={"book":"kitap","table":"masa"}
print(sozluk)
print(type(sozluk))

{'book': 'kitap', 'table': 'masa'}
<class 'dict'>


In [68]:
print(sozluk["table"])

masa


sözlüklere integer, float, string ya da tuple veri tipleri kullanılırken listeler ve sözlükler kullanılmaz.

veri ekleme

In [69]:
sozluk["pencil"]="kalem"
print(sozluk)

{'book': 'kitap', 'table': 'masa', 'pencil': 'kalem'}


veri güncelleme

In [70]:
sozluk["book"]="kitaplar"
print(sozluk)

{'book': 'kitaplar', 'table': 'masa', 'pencil': 'kalem'}


veri silme

In [71]:
del(sozluk["book"])
print(sozluk)

{'table': 'masa', 'pencil': 'kalem'}


value'nin sözlük olması

In [72]:
sozlukvalue={1:{"TL":"Türkiye"}}
print(sozlukvalue)

{1: {'TL': 'Türkiye'}}


sözlük metodları
-keys():sözlükteki keyleri verir.
-values():sözlükteki valueleri verir.
-items():sözlükteki key ve value çiftlerini verir.

In [73]:
sozluk.keys()

dict_keys(['table', 'pencil'])

In [74]:
sozluk.values()

dict_values(['masa', 'kalem'])

In [75]:
sozluk.items()

dict_items([('table', 'masa'), ('pencil', 'kalem')])

string parçalama

In [77]:
x="yetgen"
print(x[2:5])

tge


In [82]:
x="yetgen"
print(x[2:])

tgen


In [83]:
x="yetgen"
print(x[:2])

ye


In [84]:
print(x[::-1])

negtey


string metodları
-len():stringin uzunluğunu verir.

In [85]:
print(len(x))

6


-upper():stringin tüm harflerini büyük harfe çevirir.

In [86]:
x.upper()

'YETGEN'

-lower():stringin tüm harflerini küçük harfe çevirir.

In [87]:
x.lower()

'yetgen'

-capitalize():stringin ilk harfini büyük harfe çevirir.

In [88]:
x.capitalize()

'Yetgen'

-swapcase():stringin tüm büyük harflerini küçük harfe, küçük harflerini büyük harfe çevirir.

In [89]:
x.swapcase()

'YETGEN'

-replace():stringin içerisindeki veriyi değiştirir.

In [90]:
x.replace("e","a")

'yatgan'

-title():her kelimenin ilk harfini büyük yapar.

In [5]:
x="hazal kocaoğlu"
x.title()

'Hazal Kocaoğlu'

split():stringi parçalar.

In [92]:
bilgi="hazal kocaoğlu 20 istanbul"
print(bilgi.split(" "))

['hazal', 'kocaoğlu', '20', 'istanbul']


strip():stringin başındaki ve sonundaki boşlukları siler.

In [93]:
bosluk="       yetgen        "
print(bosluk.strip())

yetgen


-startswith():stringin belirtilen karakterle başlayıp başlamadığını kontrol eder.
-endswith():stringin belirtilen karakterle bitip bitmediğini kontrol eder.

In [94]:
yetgen="Yetgen"
print(yetgen.startswith("Y"))

True


In [95]:
yetgen="Yetgen"
print(yetgen.startswith("y"))

False


In [96]:
print(yetgen.endswith("en"))

True


-find():stirngin içerisindeki verinin indexini verir.eğer veri yoksa -1 döndürür.
-index():stringin içerisindeki verinin indexini verir. eğer veri yoksa ValueError hatası verir.


In [97]:
print(yetgen.find("en"))

4


4. indexten başladı demek

In [98]:
print(yetgen.find("m"))

-1


öyle bir index yok demek

In [99]:
print(yetgen.index("en"))

4


In [100]:
print(yetgen.index("m"))

ValueError: substring not found

içerisinde böyle bir index olmadığı için hata verdi.

In [ ]:
x=("hazal","kocaoğlu")
y=" "
print(y.join(x))

join burada y'nin x'i boşlukla ayırmasını sağladı.

In [6]:
string = "hello"
result = string.islower()
print(result)  # True

string = "Hello"
result = string.islower()
print(result)  # False

True
False


-isalpha():stringin tüm karakterlerinin sadece harflerden oluşup oluşmadığını kontrol eder.

In [102]:
print("abc".isalpha())

True


-isdigit():stringin tüm karakterlerinin rakam olup olmadığını kontrol eder.

In [103]:
print("123".isdigit())

True


def is_leap(year):
    leap=False
    #write your logic here
    
    return leap
year=int(input())

In [104]:
def is_leap(year):
    leap=False
    if year%4==0:
        if year%100==0 and year%400!=0:
            leap=False
        else:
            leap=True
    return leap

year=int(input())
print(is_leap(year))

True


Task
Apply your knowledge of the .add() operation to help your friend Rupal.

Rupal has a huge collection of country stamps. She decided to count the total number of distinct country stamps in her collection. She asked for your help. You pick the stamps one by one from a stack of  country stamps.

Find the total number of distinct country stamps.
Input Format
The first line contains an integer , the total number of country stamps.
The next  lines contains the name of the country where the stamp is from. 
Constraints

Output Format
Output the total number of distinct country stamps on a single line.
Sample Input
7
UK
China
USA
France
New Zealand
UK
France 
Sample Output
5
Explanation
UK and France repeat twice. Hence, the total number of distinct country stamps is  (five).

In [ ]:
n = int(input("Enter the number of country stamps: "))

# Step 2: Initialize an empty set to store country stamps
country_stamps = set()

# Step 3: Read each country name and add it to the set
for _ in range(n):
    country_name = input("Enter the name of the country: ")
    country_stamps.add(country_name)

# Step 4: Output the total number of distinct country stamps
print(len(country_stamps))

In [105]:
n=int(input())
s=set()

for i in range(n):
    country=input()
    s.add(country)
print(len(s))

2


In [2]:
# Çalışan bilgileri
calisanlar = {
    "Mehmet Yağız": ["Adana", 40, "Direktör"],
    "Ayşe Demir": ["Ankara", 30, "Mühendis"],
    "Ahmet Yılmaz": ["İstanbul", 25, "Yazılımcı"],
    "Fatma Kaya": ["İzmir", 35, "Pazarlama Müdürü"],
    "Ali Can": ["Bursa", 28, "Analist"]
}

# Kullanıcıdan isim alıp, bilgileri görüntüleyen fonksiyon
def calisan_bilgilerini_goster():
    isim = input("Lütfen bilgilerini görüntülemek istediğiniz çalışanın ismini girin: ")
    if isim in calisanlar:
        memleket, yas, gorev = calisanlar[isim]
        print(f"{isim} = Memleket: {memleket} Yaş: {yas} Görev: {gorev}")
    else:
        print("Girilen isimde bir çalışan bulunamadı.")

# Fonksiyonu çağır
calisan_bilgilerini_goster()


Mehmet Yağız = Memleket: Adana Yaş: 40 Görev: Direktör


set yapısı otomatik olarak tekrar eden elemanları filtreler:

In [1]:
numbers = [5, 10, 10, 15, 15, 15, 20, 20, 20, 20]
unique_numbers = list(set(numbers))
print(unique_numbers)

[10, 20, 5, 15]


eğer elemanların sırasını korumak istiyorsan append kullanabilirsin.

In [2]:
numbers = {5, 10, 10, 15, 15, 15, 20, 20, 20, 20}
unique_numbers = {}
for number in numbers:

    if number not in unique_numbers:
        unique_numbers.append(number)

print(unique_numbers)

AttributeError: 'dict' object has no attribute 'append'

sözlüğe bu şekilde eleman ekleyemiyormuşuz, bu yüzden hata verdi, listeye çevirelim.

In [3]:
numbers=[5,10,10,15,15,15,20,20,20,20]
uniquenumbers=[]
for number in numbers:
    if number not in uniquenumbers:
        uniquenumbers.append(number)

print(uniquenumbers)

[5, 10, 15, 20]


küme yerine liste kullanınca sayıları küçükten büyüğe sıraladı.

appendi listeye eleman eklemek için kullanıyoruz.

Şimdiyse senden `numbers` isimli listedeki tekrar eden elemanları `repeatNumbers` adındaki listeye; tekrar etmeyen elemanları `uniqueNumbers`adındaki listeye kopyalayarak yazmanı ve listeleri ekrana bastırmanı bekliyoruz

```
>Output
Tekrar Eden Elemanlar: [10, 10, 15, 15, 15, 20, 20, 20, 20]
Tekrar Etmeyen Elemanlar: [5]

In [ ]:
numbers = [5, 10, 10, 15, 15, 15, 20, 20, 20, 20]
repeatNumbers = []
uniqueNumbers = []

for number in numbers:
    if numbers.count(number) > 1:
        repeatNumbers.append(number)
    elif number not in uniqueNumbers:
        uniqueNumbers.append(number)

# Tekrar etmeyen elemanları bulmak için set kullanıyoruz
uniqueNumbers = [number for number in numbers if numbers.count(number) == 1]

print("Tekrar Eden Elemanlar:", repeatNumbers)
print("Tekrar Etmeyen Elemanlar:", uniqueNumbers)

numbers.count(number) numbers listesinde number'ın kaç tane olduğunu bulmamızı sağlıyor.

`ogrenciler` adında bir sözlük oluşturunuz. Kullanıcıdan döngü yardımıyla 3 öğrenci için veri girmesini isteyerek öğrencilerin sırasıyla okul numarası, isim, soy isim, telefon numarası ve doğum tarihi bilgilerini alınız. Aldığınız öğrenci bilgilerini yine aynı döngü yardımıyla `ogrenciler` adındaki sözlükte saklayınız. Daha sonra öğrenci bilgilerinin bulunduğu sözlük yapısını ekrana bastırınız.

In [7]:
# Öğrenciler için boş bir sözlük oluşturuyoruz
ogrenciler = {}

# 3 öğrenci için bilgileri kullanıcıdan alıyoruz
for i in range(3):
    print(f"\n{i+1}. öğrenci bilgilerini giriniz:")
    okul_numarasi = input("Okul Numarası: ")
    isim = input("İsim: ")
    soy_isim = input("Soy İsim: ")
    telefon_numarasi = input("Telefon Numarası: ")
    dogum_tarihi = input("Doğum Tarihi (GG/AA/YYYY): ")
    
    # Her öğrenci için bir iç sözlük oluşturup bilgileri ekliyoruz
    ogrenciler[okul_numarasi] = {
        "isim": isim,
        "soy_isim": soy_isim,
        "telefon_numarasi": telefon_numarasi,
        "dogum_tarihi": dogum_tarihi
    }

# Öğrenci bilgilerini içeren sözlüğü ekrana bastırıyoruz
print("\nÖğrencilerin bilgileri:")
print(ogrenciler)


1. öğrenci bilgilerini giriniz:

2. öğrenci bilgilerini giriniz:

3. öğrenci bilgilerini giriniz:

Öğrencilerin bilgileri:
{'': {'isim': '', 'soy_isim': '', 'telefon_numarasi': '', 'dogum_tarihi': ''}}


In [ ]:
1. öğrenci bilgilerini giriniz:
Okul Numarası: 101
İsim: Ali
Soy İsim: Yılmaz
Telefon Numarası: 555-1234
Doğum Tarihi (GG/AA/YYYY): 01/01/2000

2. öğrenci bilgilerini giriniz:
Okul Numarası: 102
İsim: Ayşe
Soy İsim: Demir
Telefon Numarası: 555-5678
Doğum Tarihi (GG/AA/YYYY): 15/05/2001

3. öğrenci bilgilerini giriniz:
Okul Numarası: 103
İsim: Mehmet
Soy İsim: Kara
Telefon Numarası: 555-9101
Doğum Tarihi (GG/AA/YYYY): 20/10/2002

Öğrencilerin bilgileri:
{'101': {'isim': 'Ali', 'soy_isim': 'Yılmaz', 'telefon_numarasi': '555-1234', 'dogum_tarihi': '01/01/2000'}, '102': {'isim': 'Ayşe', 'soy_isim': 'Demir', 'telefon_numarasi': '555-5678', 'dogum_tarihi': '15/05/2001'}, '103': {'isim': 'Mehmet', 'soy_isim': 'Kara', 'telefon_numarasi': '555-9101', 'dogum_tarihi': '20/10/2002'}}


print(f"\n{i+1}. öğrenci bilgilerini giriniz:") 

Python'da "\" (backslash) karakteri, özel kaçış dizilerini belirtmek için kullanılır. Örneğin, yeni bir satır başlatmak için "\n" kaçış dizisi, bir tab karakteri için "\t" kaçış dizisi kullanılır. Bu karakterler, belirli metin biçimlendirmesi veya kontrol karakterlerini temsil eder.

In [8]:
print("Birinci satır\nİkinci satır")

Birinci satır
İkinci satır


In [9]:
print("Ad\tSoyad")
print("Ali\tYılmaz")

Ad	Soyad
Ali	Yılmaz


In [ ]:
# Öğrenciler sözlüğünü oluştur
ogrenciler = {}

# 3 öğrenci için veri girişi
for i in range(3):
    print(f"\n{i+1}. öğrenci bilgilerini giriniz:")
    okul_no = input("Okul Numarası: ")
    isim = input("İsim: ")
    soy_isim = input("Soy İsim: ")
    telefon_no = input("Telefon Numarası: ")
    dogum_tarihi = input("Doğum Tarihi: ")
    
    # Öğrenci bilgilerini bir sözlükte sakla
    ogrenci_bilgileri = {
        "isim": isim,
        "soy_isim": soy_isim,
        "telefon_no": telefon_no,
        "dogum_tarihi": dogum_tarihi
    }
    
    # Öğrenci bilgilerini ana sözlükte okul numarası ile sakla
    ogrenciler[okul_no] = ogrenci_bilgileri

# Öğrenci bilgilerinin bulunduğu sözlüğü ekrana bastır
print("\nÖğrenci Bilgileri:")
for okul_no, bilgiler in ogrenciler.items():
    print(f"\nOkul Numarası: {okul_no}")
    for key, value in bilgiler.items():
        print(f"{key}: {value}")

1. print("\nÖğrenci Bilgileri:")
Bu satır, ekrana "Öğrenci Bilgileri:" başlığını yazdırır. \n karakteri, yeni bir satır eklemek için kullanılır, böylece bu yazıdan önce bir boş satır olur.

2. for okul_no, bilgiler in ogrenciler.items():
Bu döngü, ogrenciler sözlüğünün her bir anahtar-değer çiftini iterasyonla işler.

ogrenciler.items() ifadesi, ogrenciler sözlüğündeki tüm (anahtar, değer) çiftlerini döner.
okul_no değişkeni, sözlükteki her bir anahtarı (okul numarası) temsil eder.
bilgiler değişkeni, bu anahtara karşılık gelen değeri (öğrenci bilgileri sözlüğü) temsil eder.
3. print(f"\nOkul Numarası: {okul_no}")
Bu satır, her öğrenci için okul numarasını ekrana yazdırır. \n karakteri, okul numarasından önce bir boş satır ekler.

f string (f-string) kullanılarak okul_no değişkeninin değeri doğrudan string içine yerleştirilir.
4. for key, value in bilgiler.items():
Bu iç döngü, her bir öğrenci bilgisi sözlüğünün anahtar-değer çiftlerini iterasyonla işler.

bilgiler.items() ifadesi, bilgiler sözlüğündeki tüm (anahtar, değer) çiftlerini döner.
key değişkeni, öğrenci bilgileri sözlüğündeki her bir anahtarı (örneğin, isim, soy isim) temsil eder.
value değişkeni, bu anahtara karşılık gelen değeri (örneğin, Ali, Yılmaz) temsil eder.
5. print(f"{key}: {value}")
Bu satır, her bir öğrenci bilgisi anahtar-değer çiftini ekrana yazdırır.

f string kullanılarak key ve value değişkenlerinin değerleri doğrudan string içine yerleştirilir.
Bu, öğrenci bilgilerini "isim: Ali", "soy_isim: Yılmaz" gibi formatta ekrana yazdırır.

`ogrenciler` adında bir sözlük oluşturunuz. Kullanıcıdan döngü yardımıyla 3 öğrenci için veri girmesini isteyerek öğrencilerin sırasıyla okul numarası, isim, soy isim, telefon numarası ve doğum tarihi bilgilerini alınız. Aldığınız öğrenci bilgilerini yine aynı döngü yardımıyla `ogrenciler` adındaki sözlükte saklayınız. Daha sonra öğrenci bilgilerinin bulunduğu sözlük yapısını ekrana bastırınız.

bu soruyu tekrar çöz


list comprehension

In [ ]:
do this for this collection in this situation
[x**2 for x in range(0,50) if x%3==0]

In [3]:
#klasik yöntem
liste=[1,2,3,4,5,6,7,8,9,10]
yeniliste=[]
for i in liste:
    yeniliste.append(i*i)
print(yeniliste)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [1]:
#list
liste=[1,2,3,4,5,6,7,8,9,10]
yeniliste=[i*i for i in liste]
print(yeniliste)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
liste1=[[1,2,3],[4,5,6,7,8],[9,10,11,12,13,14,15]]
liste2=[x for i in liste1 for x in i]
print(liste2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [10]:
liste1=[[1,2,3],[4,5,6,7,8],[9,10,11,12,13,14,15]]
for i in liste1:
    for x in i:
        print(x)
print(liste2)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [11]:
liste1=[1,2,3,4,5,6,7,8,9,10]
liste2=[i for i in liste1 if not(i==4 or i==9)]
print(liste2)

[1, 2, 3, 5, 6, 7, 8, 10]


fonksiyonlar
-bir kodu birçok yerde kullanmamız gerekiorsa, her yerde tekrar tekrar yazmayı önler. programlamanın temeli DRY(don't repeat yourself-kendini tekrar etme)
-fonksiyonların içindeki değişkenler yereldir, yani bir fonksiyonun içinde bir değişken tanımladığınızda, o değişkeni fonksiyonun dışına çağıramayız. çünkü o değişken o fonksiyona özeldir ve globalde kullanılamaz.
-ne zaman bir fonksiyon çağrıiırsa, fonksiyonu yazdıktan sonra yapmalısınız.
-fonksiyon tamamlamanın yapısı şu şekildedir;
        def fonksiyonunadı(parametre1,parametre2,...(opsiyonel)):
        #fonksiyon bloğu
        yapılacak işlemler
        #dönüş değeri-opsiyonel
-tanımlanan bir fonksiyonun kullanılmasına programlama dillerinde Fonksiyon Çağrısı denmektedir. o halde selamla fonksiyonumuzu nasıl çağıracağımızı öğrenelim. fonksiyon çağrısı şu şekilde yapılabilmektedir;
        fonksiyonadı(argüman1,argüman2,argüman3,...)

In [12]:
def selamla():
    print("merhaba")

selamla()
selamla()

merhaba
merhaba


argüman:
-işlev çağrılırken parantez içindeki işlevlere iletilen değerler(string, number,vb.)(ör. islevadı(argüman))
-eğer fonksiyon çağrılırken bir argüman yoksa bu argümanın değeri none olacaktır. bu nedenle fonksiyonun içinde ifade edilecek bir değer yoksa belirlenen değeri kullanılmalıdır.
-birden fazla parametre olabilir.her biri virgülle ayrılır.

In [14]:
def helloworld(name="ziyaretçi"):
    print("merhaba", name)

helloworld()
helloworld("hazal")

merhaba ziyaretçi
merhaba hazal


In [15]:
def topla(sayi1,sayi2,sayi3):
    toplam=sayi1+sayi2+sayi3
    print(toplam)

topla(1,2,3)

6


In [18]:
def merhaba(name="hazal",surname="kocaoğlu"):
    print("sisteme hoş geldin " + name + " " + surname)
merhaba()
merhaba("ahmet")
merhaba("evrim","cantimur")

sisteme hoş geldin hazal kocaoğlu
sisteme hoş geldin ahmet kocaoğlu
sisteme hoş geldin evrim cantimur


In [19]:
def carp(sayi1=1, sayi2=1, sayi3=1):
    c=sayi1*sayi2*sayi3
    print(c)
carp(2,3,5)
carp(2,3)
carp(2)

30
6
2


In [20]:
def merhaba(dil):
    if dil=="es":
        print("hola")
    elif dil=="fr":
        print("bonjour")
    elif dil=="en":
        print("hello")
    else:
        print("merhaba")

merhaba("es")
merhaba("fr")
merhaba("en")
merhaba("tr")

hola
bonjour
hello
merhaba


return
-kodun tamammında kullanmak için işlevin kodu tamamladıktan sonra kalan değeri(sonuç değeri) döndürür.
-"return" anahtar sözcüğünden sonraki kodlar yürütülemez. bu görmezden gelindikleri anlamına gelir.
-return yardımıyla fonksiyonlar değerleri çağrıldığı yere döndürebilir ve biz de bu değerleri istediğimiz yerde kullanabiliriz.

In [21]:
def dikucgenalanihesapla(a,b):
    return(a*b)/2
print(dikucgenalanihesapla(2,3))

3.0


In [22]:
def dikucgenalanihesapla(a,b):
    return(a*b)/2
alan=dikucgenalanihesapla(2,3)
print(alan)

3.0


*args
-sınırsız sayıda parametreli fonksiyon oluşturmak için parametremizin önüne tek yıldız(*) koyabiliriz.
-isimsiz argümanlardır.

In [23]:
def sayilar(*x):
    print(x)
sayilar(4)

(4,)


In [24]:
def sayilar(*x):
    print(x)
sayilar(4,5,6,7,8,9,10)

(4, 5, 6, 7, 8, 9, 10)


In [25]:
def topla(*x):
    toplam=0
    for i in x:
        toplam+= i #toplam=toplam+1
    print(toplam)
topla(1,2,3,4,5,6,7,8,9,10)

55


**kwargs
-çift yıldızli(**) parametrelerin tek yıldızlı(*) parametrelerden en önemli farkı, fonksiyonu çağırırken anahtar değer ilişkisiyle çağırabilmemizdir.
-isimli argümanlardır.

In [26]:
def kimlikgoster(**kimlik):
    print(kimlik)
kimlikgoster(adi="hazal", soyadi="kocaoğlu", yas=20)

{'adi': 'hazal', 'soyadi': 'kocaoğlu', 'yas': 20}


In [27]:
def ornek(a,*sayilar,b,**kimlik):
    print(a)
    print(sayilar)
    print(b)
    print(kimlik)

ornek(10,20,30,40,50,b=6,adi="hazal",soyadi="kocaoğlu",yas=23)

10
(20, 30, 40, 50)
6
{'adi': 'hazal', 'soyadi': 'kocaoğlu', 'yas': 23}


pass deyimi-python programlamasında pass ifadesi null değer atama için kullanılır. pythondaki bir açıklama ve geçiş ifadesi arasındaki fark, yorumlayıcı bir yorumu tamamen yok sayarken, geçişin göz ardı edilmemesidir.

In [30]:
def carp(*sayilar):
    for sayi in sayilar:
        pass
carp(2,5)

global ve yerel değişkenler
-global değişken fonksiyonlarımızın dışında tanımladığımız değişkenlerdir.
-yerel değişkenler ise fonksiyon içinden kullanılırken, fonksiyonların içinde tanımladığımız değişkenler fonksiyon dışında kullanılamaz.

In [ ]:
#global değişken
def goster():
    #yerel değişken

In [32]:
def yazdir2():
    x=5
    print(x)
yazdir2
print(x)

15


In [33]:
def yazdir3():
    global x
    x=5
    print(x)
yazdir3()
print(x)

5
5


bir fonksiyon kendi içerisinde çağrılırsa sonsuz dögüye girer.

lambda gösterimi
-pythonda isimsiz olarak tanımladığımız fonksiyonlara lambda fonksiyonları denir.
-tek satırda yazılırlar.
-gösterimi
fonksiyonadi=lambda parametreler:yapilacakislem

In [34]:
dikucgenalanihesapla=lambda a,b:a*b/2
dikucgenalanihesapla(2,3)

3.0

In [35]:
ikiylecarp=lambda x:print(x*2)
ikiylecarp(3)

6


In [36]:
ters=lambda s: s[::-1]
print(ters("hazal"))

lazah


modüller
modül mantığı
bir python modülünü programımıza dahil ederek bu modüller içinde yazılan fonksiyonlardan ve sınıflardan kullanabilir ve programlarımızı daha efektif bir şekilde yazabiliriz.eğer modül diye bir kavram olmasaydı, programlarımızdaki her bir fonksiyonu ve sınıfı kendimiz yazmak zorunda kalacaktık.

math modülü

In [1]:
import math 
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [2]:
math.factorial(5)

120

In [3]:
math.e

2.718281828459045

In [4]:
math.floor(3.5)

3

In [5]:
math.ceil(3.2)

4

In [6]:
math.ceil(3.8)

4

from modül_adı import* ile kütüphanemizi kullanabilirsiniz.

In [1]:
from math import*
def factorial(sayi):
    print("kendi faktöriyel fonksiyonum")
    faktoriyel=1
    if(sayi==0 or sayi==1):
        return 1
    while(sayi>=1):
        faktoriyel *=sayi
        sayi-=1
    return faktoriyel
factorial(5)


kendi faktöriyel fonksiyonum


120

map fonksiyonu
parametre olarak aldığı fonksiyona,parametre olarak aldığı listenin her elemanınj sırasıyla parametre olarak gönderir.
map(fonksiyon, iterasyon yapılabilecek veritipi(liste, demet,vb),...)

In [12]:
numbers=[2,8,16,32,64]
powers=[]
def power(x):
    return x**2
powers=list(map(power,numbers))
print(powers)

[4, 64, 256, 1024, 4096]


In [14]:
liste1=[1,2,3,4]
liste2=[5,6,7,8]
liste3=[9,10,11,12,13]
list(map(lambda x,y,z:x*y*z,liste1,liste2,liste3))

[45, 120, 231, 384]

filter fonksiyonu
isminden de anlaşıldığı gibi filtreleme işlemi yapar.
filter(fonksiyon,iterasyon yapılabilen bir veritipi(liste vb.))

In [15]:
list(filter(lambda x:x%2==0,[0,1,2,3,4,5,6,7,8,9,10]))

[0, 2, 4, 6, 8, 10]

In [17]:
def asal_mi(sayi):
    i=2
    if(sayi==1):
        return False
    if (sayi==2):
        return True 
    else:
        while i<sayi:
            if(sayi%i==0):
                return False
            i+=1
    return True
list(filter(asal_mi,range(1,100)))

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

zip fonksiyonu

In [3]:
liste1=[1,2,3,4]
liste2=[5,6,7,8]
liste3=["python","java","c#","javascript"]
list(zip(liste1,liste2,liste3))

[(1, 5, 'python'), (2, 6, 'java'), (3, 7, 'c#'), (4, 8, 'javascript')]

In [19]:
sozluk1={"elma":1, "armut":2, "kiraz":3}
sozluk2={"sıfır":0,"bir":1,"iki":2}
list(zip(sozluk1,sozluk2))

[('elma', 'sıfır'), ('armut', 'bir'), ('kiraz', 'iki')]

enumarate()
ingilizcede enumerate kelimesi 'numaralandırmak' anlamına gelir. enumerate() fonksiyonun görevi de kelimenin bu anlamıyla aynıdır. yani bu fonksiyonu kullanarak nesneleri numaralandırabiliriz.

In [21]:
liste=["elma","armut","muz","kiraz"]
list(enumerate(liste))

[(0, 'elma'), (1, 'armut'), (2, 'muz'), (3, 'kiraz')]

all()
all() fonksiyonu bütün değerler True ise True, en az bir değer False ise False sonuç döndürür.

In [22]:
liste=[True,True,False]
all(liste)

False

any()
any() fonksiyonu bütün değerler False ise False, en az bir değer True ise True değerini döndürür.

In [23]:
liste=[True,True,False]
any(liste)

True

hata yönetimi
python programlarında bazen bir değişkenin tanımlanmadan kullanılmaya çalıştırılması, bazen de yapılamayacak bir aritmetik işlemin yapılması pythonda hatalara yol açar. ancak bu istisnai durumlarda, hataların türüne göre programlarımızı daha güvenli bir şekilde yazabiliriz. yani hata çıkarabilecek kodlarımızı öngörerek bu hatalarımızı programlarımızda yakalayabiliriz.

In [24]:
print(a)

NameError: name 'a' is not defined

In [25]:
print(2/0)

ZeroDivisionError: division by zero

In [26]:
print "merhaba"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1475024089.py, line 1)

try,except blokları
try,except bloklarının yapısı şu şekildedir;
try:
hata çıkarılanilecek kodlar buraya yazılıyor.
eğer hata çıkarsa program uygun olan except bloğuna  girecek.
hata oluşursa try bloğunun geri kalanındaki işlemler çalışmayacak.
except hata1:
hata1 oluştuğunda burası çalışacak.
except hata2:
hata2 oluştuğunda burası çalışacak.

In [27]:
try:
    a=int("abcd")
    print("program burada")
except:
    print("hata oluştu")

hata oluştu


In [29]:
try:
    a=int("abcd")
except ValueError:
    print("hata oluştu")

print("bloklar sona erdi")

hata oluştu
bloklar sona erdi


In [31]:
try:
    a=int(input("sayı 1:  "))
    b=int(input("sayı 2: "))
    print(a/b)
except ValueError:
    print("inputları doğru giriniz")
except ZeroDivisionError:
    print("sayı 0'a bölünemez")

sayı 0'a bölünemez


In [33]:
try:
    a=int(input("sayı 1:  "))
    b=int(input("sayı 2: "))
    print(a/b)
except (ZeroDivisionError, ValueError):
    print("value error ya da ZeroDivisionError")

value error ya da ZeroDivisionError


try-except-else
*try bloğununn içinde hata oluşursa except bloğuna girer.
*try bloğunun içinde hata oluşmazsa else bloğuna girer.

try:
    hata çıkarabilecek kodlar buraya yazılır.
except Hata1:
    Hata1 oluştuğunda burası çalışacak.
else:
    Hata oluşmazsa burası çalışacak.

In [34]:
try:
    a=int(input("sayı 1: "))
    b=int(input("sayı 2: "))
    print(a/b)
except ZeroDivisionError:
    print("sayı 0'a bölünemez.")
except ValueError:
    print("yanlış değer girdiniz")
else:
    print("program çalıştı")

sayı 0'a bölünemez.


try-except-finally
try:
    hata çıkarabilecek kodlar buraya yazılır.
except Hata1:
    Hata1 oluştuğunda burası çalışacak.
finally:
    Kesin olarak her zaman çalışacak.

In [35]:
try:
    a=int(input("sayı 1: "))
    b=int(input("sayı 2: "))
    print(a/b)
except ZeroDivisionError:
    print("sayı 0'a bölünemez.")
except ValueError:
    print("yanlış değer girdiniz")
finally:
    print("program sona erdi.")

0.6
program sona erdi.


In [39]:
try:
    liste=list(range(100))
    print(liste[101])
except:
    print("hata oluştu")
finally:
    liste.clear()
print(len(liste))

hata oluştu
0


Hata Fırlattırma
*hataları firlatmak için raise kullanılır.
raise HataAdı(opsiyonel hata mesajı)

In [44]:
def tersCevir(s):
    if(type(s) !=str ):
        raise ValueError("lütfen doğru bir input giriniz")
    else:
        returns[::-1]

try:
    print(tersCevir(12))
except ValueError:
    print("programda hata oluştu")

programda hata oluştu


# Problem 2

2 YetGen lideri ders sırasında canları sıkılınca oyun oynamak isterler. Ancak hangi oyunu oynayacaklarına karar veremezler ve son olarak kendi oyunlarını yazmaya karar verirler.
Liderlerimizin kodlamak istediği oyun kuralları şöyledir:
- Oyunda random olarak 0 ile 100 arasında bir sayı tutulur.
- Kullanıcıdan bilgisayarın tuttuğu sayıyı tahmin etmesi için bir sayı girmesini istenir.
- Eğer kullanıcının girdiği sayı bulunması gereken sayıdan küçükse  tahmininizi yükseltin, büyükse tahmininizi düşürün şeklinde bir çıktı verilir.
- Oyunun gerçeğe yakın olması için bilgisayarın çalışmasını simgelemek için 1 saniye bekleme süresi tanınır.
- Kullanıcı 5 hakkı vardır. 5 hakkı da kullanıp sayıyı bulamazsa oyunu kaybeder.

In [1]:
import time
import random

dogrusayi=random.randint(1,100)

haklar=5

while haklar>0:
    kullanicisayi=int(input("1-100 arası bir sayı gir:"))

    if kullanicisayi<dogrusayi:
        haklar-=1
        if haklar>0:
            print(f"tahminini yükselt.{haklar} hakkın kaldı.")

        else:
            print("oyunu kaybettin.")

    elif kullanicisayi>dogrusayi:
        haklar-=1
        if haklar>0:
            print(f"tahminini düşür.{haklar} hakkın kaldı.")

        else:
            print("oyunu kaybettin.")

    else:
        print("tebrikler!doğru tahmin ettiniz.")
        break
    
    if haklar>0:
        print("bekle...")
        time.sleep(1)
        print("1 saniye sonra")

if haklar==0:
    print(f"doğru sayı {dogrusayi} idi.")


tahminini düşür.4 hakkın kaldı.
bekle...
1 saniye sonra
tahminini düşür.3 hakkın kaldı.
bekle...
1 saniye sonra
tahminini düşür.2 hakkın kaldı.
bekle...
1 saniye sonra
tahminini yükselt.1 hakkın kaldı.
bekle...
1 saniye sonra
oyunu kaybettin.
doğru sayı 10 idi.


dosya okuma işlemleri
-dosya açmak ve oluşturmak için open() kullanılır.
-open(dosyaIsmi, dosyaModu)
-dosyaModu: dosyayı hangi modda açacağını belirtir.
-r:okuma modunda açmayı sağlar. belirtilen konumda dosya olması gerekir.
-close(): dosyayı kapatır.

In [14]:
f=open("bilgiler.txt")
print(f)

<_io.TextIOWrapper name='bilgiler.txt' mode='r' encoding='utf-8'>


In [13]:
try:
    file=open("bilgiler2.txt","r",encoding="utf-8")
except:
    print("ben bu dosyayı bulamadım")

ben bu dosyayı bulamadım


elimizde bilgiler.txt2 yok, bizim oluşturduğumuz doysa bilgiler.txt dosyasıydı bu yüzden dosyayı bulamadı. bilgiler.txt ile tekrar deneyelim ve sonuca bakalım.

In [12]:
try:
    file=open("bilgiler.txt","r",encoding="utf-8")
except:
    print("ben bu dosyayı bulamadım")

hiçbir çıktı vermedi çünkü dosyayı buldu

In [11]:
file=open("bilgiler.txt","r",encoding="utf-8")

for i in file:
    print(i)
file.close()

YetGen

Jump

Pyhton 

2


read() fonksiyonu
read() fonksiyonu eğer içine hiçbir değer vermezsek bütün dosyamızı okuyacaktır.

In [10]:
file=open("bilgiler.txt","r", encoding="utf-8")
icerik=file.read()
print("1. okuma dosya içeriği\n", icerik, sep=" ")
icerik2=file.read()
print("2. okuma dosya içeriği\n", icerik, sep=" ")
file.close()

1. okuma dosya içeriği
 YetGen
Jump
Pyhton 
2
2. okuma dosya içeriği
 YetGen
Jump
Pyhton 
2


read() fonskiyonuyla bir dosyayı okuduğumuzda dosya imlecimiz dosyanın en sonuna gider ve read() donksiyonu 2. okumada artık boş string döner.

readline() fonksiyonu
her çalıştırıldığında bir satır okur.

In [17]:
file=open("bilgiler.txt","r", encoding="utf-8")
print(file.readline())

YetGen



In [18]:
print(file.readline())

Jump



In [19]:
print(file.readline())

Pyhton 



In [20]:
print(file.readline())

2


In [21]:
print(file.readline())

sadece bu sonuncunun boş dönmesi gerekiyor çünkü dosyamızda 3 karakter vardı ama biz 4 kod yazdık dolayısıyla son kodumuzda hiçbir şey bulamayacak

In [23]:
file.close()

In [25]:
print(file.readlines())

ValueError: I/O operation on closed file.

hata veriyor çünkü önceki aşamada dosyayı kapat komutu vermiştik, şu an tekrar dosyayı aç komutu vermeden işlem yapamayız.

In [2]:
file=open("bilgiler.txt","r", encoding="utf-8")
print(file.readlines())
file.close()

['YetGen\n', 'Jump\n', 'Pyhton \n', '2']


dosya yazma 
w: yazma modu. dosyayı konumda oluşturu. eğer dosya mevcut ise, dosyayı siler ve yeni bir dosya oluşturur. write fonksiyonu ile dosyamıza yazıyoruz.

In [28]:
file=open("bilgiler.txt","w",encoding="utf-8")
file.write("YetGen\n")
file.close()

a: append(ekleme) modudur. dosya konumda varsa oluşturur, dosya konumda varsa ekleme işlemi yapar.

r+:hem okuma hem yazma modudur. dosya konumda yoksa hata verir.

In [31]:
file=open("bilgiler.txt","a", encoding="utf-8")
file.write("Jump\n")
file.close()

In [34]:
file=open("bilgiler.txt","r+",encoding="utf-8")
file.write("Pyhton\n")
file.read()
file.close()

dosyaları otomatik kapatma
with open(dosya_adı, dosya_kipi) as file:
dosya işlemleri

In [35]:
with open("bilgiler.txt","r",encoding="utf-8") as file:
    for i in file:
        print(i)

Pyhton

Jump

Jump

Jump



dosyayı ileri-geri sarmak
-seek() metodunu kullanarak istediğiniz bayt konumuna dönebilirsiniz.
-dosyanın hangi bayt konumunda bulunduğunuzu öğrenmek isterseniz de tell() metodunu kullanabilirsiniz.

In [39]:
with open("bilgiler.txt","r",encoding="utf-8") as file:
    file.seek(20)
    print(file.tell())

20


In [40]:
with open("bilgiler.txt","r",encoding="utf-8") as file:
    file.seek(5)
    icerik=file.read(10)
    print(icerik)
    file.seek(0)
    icerik2=file.read(6)
    print(icerik2)

n
Jump
Jum
Pyhton


dosyanın sonunda değişiklik yapmak

In [41]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    file.seek(10)
    file.write("Deneme")

In [42]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    print(file.read())

Pyhton
JumDeneme
Jump



dosyanın başında değişiklik yapmak

In [44]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    icerik=file.read()
    icerik="Deneme\n"+ icerik
    file.seek(0)
    file.write(icerik)

In [45]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    print(file.read())

Deneme
Deneme
Pyhton
JumDeneme
Jump



dosyanın ortasında değişiklik yapmak 

In [46]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    liste=file.readlines()
    liste.insert(3, "deneme\n")
    file.seek(0)
    file.writelines(liste)

In [47]:
with open("bilgiler.txt","r+",encoding="utf-8") as file:
    icerik=file.read()
    print(icerik)

Deneme
Deneme
Pyhton
deneme
JumDeneme
Jump



#nesne yönelimli programlama(OOP)
-DRY(don't repeat yourself)

class
sınıflar veya classlar objelerimizi oluştururken objelerin özelliklerini ve metodlarını tanımladığımız bir yapıdır.

In [1]:
class Araba():
    #sınıf özellikleri(attribute)
    model="reanult megane"
    renk="gümüş"
    beygirGucu=110
    silindir=4

obje oluşturma 
obje_ismi=sınıf_ismi(parametreler(opsiyonel))
özelliklere erişme
obje_ismi.özellik_ismi

In [2]:
araba1=Araba()
print(araba1.model)
print(araba1.renk)
print(araba1.beygirGucu)
print(araba1.silindir)

reanult megane
gümüş
110
4


In [3]:
class Animal:
    name="kuş"
    print(name)

kuş


init()
pyhtonda yapıcı(constructor) fonksiyon olarak tanımlanmaktadır. bu metod objelerimiz oluşturulurken otomatik olarak ilk çağrılan fonksiyondur. bu metodu özel olarak tanımlayarak objelerimizi farklı değerlerle oluşturabiliriz.

In [4]:
class Araba:
    def __init__(self):
        print("init fonksiyonu çalıştı")

araba=Araba()

init fonksiyonu çalıştı


self anahtar kelimesi objeyi oluşturduğumuz zaman o objeyi gösteren bir referanstır ve metodlarımızda en başta bulunması egreken bir parametredir.

In [5]:
class Araba():
    def __init__(self,model,renk,beygir,silindir):
        self.model=model
        self.renk=renk
        self.beygir=beygir
        self.silindir=silindir
        

In [8]:
araba2=Araba("peugot 301", "beyaz", 90, 4)
print(araba2.model)

peugot 301


uygulama
-comment isminde bir bir sınıf oluşturunuz.
-comment sınıfı username,text,likes,dislikes isminde özelliklere sahip olsun.
-5 adet farklı comment oluşturup döngü yardımıyla yorumları ekrana yazdırınız.

In [10]:
class Comment:
    def __init__(self,username,text,likes,dislikes):
        self.username=username
        self.text=text
        self.likes=likes
        self.dislikes=dislikes

c1=Comment("hazal","python öğreniyorum",45,1)
c2=Comment("ahmet","jumperlar çok güzel çalışıyor",50,10)
c3=Comment("emirhan", "bu seneki jumperlar çok başarılı",100,5)
c4=Comment("eslem","liderler ekibi bir harika",50,1)
c5=Comment("jumper","liderlerimiz bizim için çok çalışıyor",200,0)

comments=[c1,c2,c3,c4,c5]

for c in comments:
    print(f"{c.username}:{c.text} yorumunu yapıp {c.likes} beğeni aldı.{c.dislikes} dislikes aldı")

hazal:python öğreniyorum yorumunu yapıp 45 beğeni aldı.1 dislikes aldı
ahmet:jumperlar çok güzel çalışıyor yorumunu yapıp 50 beğeni aldı.10 dislikes aldı
emirhan:bu seneki jumperlar çok başarılı yorumunu yapıp 100 beğeni aldı.5 dislikes aldı
eslem:liderler ekibi bir harika yorumunu yapıp 50 beğeni aldı.1 dislikes aldı
jumper:liderlerimiz bizim için çok çalışıyor yorumunu yapıp 200 beğeni aldı.0 dislikes aldı


numpy
-numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
-Veri analizinde kullanılır.
-Bilgisayar kurmak için pip insall numpy komutu ile kurulabilir.
-Bilimsel hesaplamalar için kullanılır.
-Arraylar/ çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
-Temelleir 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
-Listelere benzerdir. Fakat verimli veri saklama ve evktör işlemleri için Numpy kullanılır.

neden numpy?

In [1]:
#klasik yöntem ile
a=[1,2,3,4]
b=[2,3,4,5]
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [ ]:
#numpy ile
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

.reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.

In [4]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
multi=x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arraylerin boyutlarını öğrenebiliriz.

In [5]:
print(multi.shape)

(3, 3)


In [6]:
print;(x.shape)

(9,)

.ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [7]:
print(x.ndim)

1


In [8]:
print(multi.ndim)

2


birleştirme(concatenation)
-concatenate() fonksiyonu ile birleştirme yapabiliriz.

In [9]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
z=np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis=0 satır bazında birleştirme yapar.
axis=1 ise sütun bazında birleştirme yapar.

In [12]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


array ayırma(splitting)
-.split() fonksiyonu ile array ayırma yapabiliriz.

In [13]:
m=np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [14]:
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz.
hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.

In [15]:
n=np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

np.arange()
-belli aralıkta sayıları oluşturmak için kullanılır.
-np.arange(start,stop,step)

In [17]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

np.zeros()
-0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

np.ones()
-1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [19]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

np.linspace()
-belli bir aralıkta sayıları oluşturmak için kullanılır.
-np.linspace(başlangıç,bitiş,bölünecek aralık)

In [20]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [21]:
np.random.randint(0,10,3)

array([2, 8, 6])

In [22]:
np.random.randint(2,22,5)

array([21, 17, 15, 16, 12])

In [24]:
npArray=np.arange(50)
npMulti=npArray.reshape(5,10)#5'e 10'luk
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


numpy array'in özellikleri
-ndim:boyut sayısı
-shape:boyut bilgisi
-size:toplam eleman sayısı
-dtype:veri tipi 

In [25]:
a=np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int64


array sıralama(sorting)
-array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [26]:
v=np.array([8,24,232,12,5,42,55])
v.sort()
print(v)

[  5   8  12  24  42  55 232]


In [27]:
m=np.random.normal(20,5,(3,3))
print(m)

[[18.64935651 13.22276446 21.33776524]
 [16.82057093 23.94903818 22.25592038]
 [28.96142756 19.02951034 27.35973834]]


In [28]:
print(np.sort(m,axis=0))

[[16.82057093 13.22276446 21.33776524]
 [18.64935651 19.02951034 22.25592038]
 [28.96142756 23.94903818 27.35973834]]


In [29]:
print(np.sort(m,axis=1))

[[13.22276446 18.64935651 21.33776524]
 [16.82057093 22.25592038 23.94903818]
 [19.02951034 27.35973834 28.96142756]]


index ile elemanlara erişmek
-aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [32]:
a=np.random.randint(10,size=10)
print(a[0])

5


In [33]:
print(a[-1])

4


In [35]:
a[0]=100
print(a)

[100   4   6   9   9   8   1   5   4   4]


In [36]:
x=np.random.randint(10,size=(3,5))
print(x)

[[0 6 8 2 5]
 [0 2 3 1 2]
 [7 4 2 3 9]]


In [37]:
print(x[0,0])

0


In [38]:
print(x[1,1])

2


In [39]:
x[1,4]=100
print(x)

[[  0   6   8   2   5]
 [  0   2   3   1 100]
 [  7   4   2   3   9]]


In [42]:
x[1,4]=3.14
print(x)

[[0 6 8 2 5]
 [0 2 3 1 3]
 [7 4 2 3 9]]


slicing ile elemanlara erişmek(array alt kümesine erişmek)

In [43]:
a=np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [44]:
print(a[0:3])

[20 21 22]


In [45]:
print(a[:3])

[20 21 22]


In [46]:
print(a[3:])

[23 24 25 26 27 28 29]


In [47]:
print(a[1::2])

[21 23 25 27 29]


In [48]:
print(a[0::2])

[20 22 24 26 28]


In [49]:
print(a[2::2])

[22 24 26 28]


In [50]:
print(a[1::5])

[21 26]


In [51]:
b=np.random.randint(10,size=[5,5])
print(b)

[[2 1 2 0 4]
 [6 9 1 5 9]
 [0 8 9 8 8]
 [5 0 9 5 7]
 [9 8 9 8 3]]


In [52]:
print(b[:,0])

[2 6 0 5 9]


In [53]:
print(b[:,1])

[1 9 8 0 8]


In [54]:
print(b[0,:])

[2 1 2 0 4]


In [55]:
print(b[1,:])

[6 9 1 5 9]


In [57]:
print(b[0:2,0:3])

[[2 1 2]
 [6 9 1]]


In [58]:
print(b[::2,::2])

[[2 2 4]
 [0 9 8]
 [9 9 3]]


alt küme üzerinde işlem yapmak

In [59]:
alt_b=b[0:3,0:2]
alt_b

array([[2, 1],
       [6, 9],
       [0, 8]])

In [60]:
alt_b[0,0]=100
alt_b[1,1]=200
alt_b

array([[100,   1],
       [  6, 200],
       [  0,   8]])

In [61]:
print(b)

[[100   1   2   0   4]
 [  6 200   1   5   9]
 [  0   8   9   8   8]
 [  5   0   9   5   7]
 [  9   8   9   8   3]]


fancy index
-bir liste içine bu arrayden istediğimiz indisleri koyarak o indislerdeki verileri alabiliriz.

In [62]:
v=np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [ ]:
a[0]=100
print(a)

[100   4   6   9   9   8   1   5   4   4]


In [63]:
yetgen=[1,3,5]
print(v[yetgen])

[ 3  9 15]


In [64]:
m=np.arange(9).reshape(3,3)
satir=np.array([0,1])
sutun=np.array([1,2])
print(m[satir,sutun])

[1 5]


koşullu eleman işlemleri

In [65]:
v=np.array([1,2,3,4,5])
print(v>3)

[False False False  True  True]


In [66]:
print(v[v>3])

[4 5]


In [67]:
print(v[v<3])

[1 2]


In [68]:
print(v[v>=3])

[3 4 5]


In [69]:
print(v[v<=3])

[1 2 3]


In [70]:
print(v[v!=3])

[1 2 4 5]


In [71]:
print(v[v==3])

[3]


matematiksel işlemler

In [73]:
v=np.array([1,2,3,4,5])
print(v*2)

[ 2  4  6  8 10]


In [74]:
print(v+2)

[3 4 5 6 7]


In [75]:
print(v*5/10)

[0.5 1.  1.5 2.  2.5]


In [76]:
print(v**2)

[ 1  4  9 16 25]


In [77]:
print(np.subtract(v,3)) #her birinden 3 çıkarır.

[-2 -1  0  1  2]


In [78]:
print(np.add(v,2))

[3 4 5 6 7]


In [79]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [80]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [81]:
np.power(v,2)

array([ 1,  4,  9, 16, 25])

In [82]:
np.mod(v,5)

array([1, 2, 3, 4, 0])

In [84]:
print(np.absolute(v))

[1 2 3 4 5]


In [85]:
print(np.sin(360))

0.9589157234143065


In [86]:
np.log(10)

np.float64(2.302585092994046)

iki bilinmeyenli denklem çözümü

In [88]:
# 5*x0 + x1 = 12
# x0 + 3*x1 =10
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
x=np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]


pandas
-pandas kütüphanesi veri analizi için kullanılan bir kütüphanedir.
-panel data'dan gelmektedir.
-yapısal verilerle çalışmak için kullanılır.
-veri manipülasyonu ve analizi için yazılmış açık kaynaklı bir Python kütüphanesidir.
-ekonometrik ve finansal verilerle çalışmak için kullanılır.
-2008 yılında Wes McKinney tarafından geliştirilmiştir.

pip install pandas komutu ile pandas kütüphanesini kurabiliriz.

In [1]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 591.3 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


pandas serisi oluşturma
pd.Series() ile pandas serisi oluşturabiliriz.

In [3]:
import pandas as pd
import numpy as np
seri=pd.Series([1,2,3,4,5,6,7,8,9])
print(seri)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [4]:
type(seri)

pandas.core.series.Series

.axes ile serinin başlangıç, bitiş ve adım değerlerini görebiliriz.

In [5]:
print(seri.axes)

[RangeIndex(start=0, stop=9, step=1)]


dtype ile serinin veri tipini görebiliriz.

In [6]:
print(seri.dtype)

int64


.size ile serinin boyutunu görebiliriz.

.ndim ile serinin boyut sayısını görebiliriz.

In [7]:
print(seri.size)
print(seri.ndim)

9
1


.values ile serinin değerlerini görebiliriz.

In [8]:
print(seri.values)

[1 2 3 4 5 6 7 8 9]


.head() ile serinin ilk 5 değerini görebiliriz. Eğer isterseniz .head(10) diyerek ilk 10 değeri görebilirsiniz.

In [9]:
seri.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
print(seri.head(3))

0    1
1    2
2    3
dtype: int64


.tail() ile serinin son 5 değerini görebiliriz. Eğer isterseniz .tail(10) diyerek son 10 değeri görebilirsiniz.

In [11]:
seri.tail()

4    5
5    6
6    7
7    8
8    9
dtype: int64

In [12]:
seri.tail(3)

6    7
7    8
8    9
dtype: int64

In [20]:
seri=pd.Series([99,22,332,94,5], index=["a","b","c","d","e"])

In [23]:
print(seri["a"])

99


In [24]:
print(seri["a":"c"])

a     99
b     22
c    332
dtype: int64


In [25]:
sozluk={"reg":10, "log":11, "cart":12}
seri=pd.Series(sozluk)
seri

reg     10
log     11
cart    12
dtype: int64

In [26]:
randomNumbers=np.random.randint(10,100,5)
pandas=pd.Series(randomNumbers)
print(pandas[0])

27


In [27]:
seri=pd.Series([200,121,150,99], index=["a","b","c","d"])
print(seri)

a    200
b    121
c    150
d     99
dtype: int64


In [28]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [29]:
seri.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [30]:
seri.keys

<bound method Series.keys of a    200
b    121
c    150
d     99
dtype: int64>

In [31]:
print(list(seri.items()))

[('a', 200), ('b', 121), ('c', 150), ('d', 99)]


In [32]:
"a" in seri

True

In [33]:
"g" in seri

False

In [34]:
seri[["a","b"]]

a    200
b    121
dtype: int64

In [35]:
seri["a"]=250
print(seri)

a    250
b    121
c    150
d     99
dtype: int64


pandas DataFrame oluşturma
pd.DataFrame()
-DataFrame oluşturabiliriz.
-columns parametresi ile kolon isimlerini belirleyebiliriz.
-index parametresi ile index isimlerini belirleyebiliriz.

In [37]:
l=[1,2,3,4,5]
pd.DataFrame(l, columns=["degisken_ismi"])

degisken_ismi
0              1
1              2
2              3
3              4
4              5

In [38]:
m=np.arange(1,10).reshape((3,3))
pd.DataFrame(m, columns=["1","2","3"])

1  2  3
0  1  2  3
1  4  5  6
2  7  8  9

In [39]:
df=pd.DataFrame(m, columns=["var1","var2","var3"])
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [40]:
df.columns={"degisken1","degisken2","degisken3"}
df

degisken3  degisken1  degisken2
0          1          2          3
1          4          5          6
2          7          8          9

In [41]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['degisken3', 'degisken1', 'degisken2'], dtype='object')]

In [42]:
df.shape

(3, 3)

In [43]:
df.ndim

2

In [44]:
df.size

9

In [45]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
df.tail(1)

degisken3  degisken1  degisken2
2          7          8          9

Eleman İşlemleri

In [94]:
import numpy as np
import pandas as pd

# Generating random integer arrays
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

# Creating a DataFrame from the arrays and transposing it
df = pd.DataFrame([s1, s2, s3]).transpose()

# Setting the column names
df.columns = ['s1', 's2', 's3']

# Displaying the DataFrame
print(df)

   s1  s2  s3
0   5   4   4
1   5   6   2
2   0   5   2
3   1   5   2
4   8   6   5


In [95]:
sozluk={"var1":s1, "var2":s2, "var3":s3}
df=pd.DataFrame(sozluk)

In [96]:
df

var1  var2  var3
0     5     4     4
1     5     6     2
2     0     5     2
3     1     5     2
4     8     6     5

In [97]:
df[0:1]

var1  var2  var3
0     5     4     4

In [98]:
df.index=["a","b","c","d","e"]

In [99]:
df

var1  var2  var3
a     5     4     4
b     5     6     2
c     0     5     2
d     1     5     2
e     8     6     5

In [100]:
df[0:1]

var1  var2  var3
a     5     4     4

In [101]:
df["c":"e"]

var1  var2  var3
c     0     5     2
d     1     5     2
e     8     6     5

-df.drop() ile kolon veya satır silme işlemi yapabiliriz.
-axis=1 ile kolon silme işlemi yapabiliriz.
-axis=0 ile satır silme işlemi yapabiliriz.

In [105]:
df.drop("a",axis=0)

var1  var2  var3
b     5     6     2
c     0     5     2
d     1     5     2
e     8     6     5

In [106]:
df

var1  var2  var3
a     5     4     4
b     5     6     2
c     0     5     2
d     1     5     2
e     8     6     5

implace parametresi ile değişikliği kalıcı kaydetme işlemi yapabiliriz. Diğer durumlarda değişiklikler geçici olarak kaydedilir.

In [109]:
df.drop("a", axis=0,inplace=True)

In [110]:
df

var1  var2  var3
b     5     6     2
c     0     5     2
d     1     5     2
e     8     6     5

In [111]:
l=["var1","var2","var3"]
for i in l:
    print(i in l)

True
True
True


In [136]:
df["var4"]=df["var1"]/df["var2"]
df

var1  var2  var3      var4
b     5     6     2  0.833333
c     0     5     2  0.000000
d     1     5     2  0.200000
e     8     6     5  1.333333

In [137]:
df.drop("var4", axis=1, inplace=True)
df

var1  var2  var3
b     5     6     2
c     0     5     2
d     1     5     2
e     8     6     5

In [138]:
l=["var1","var2"]
df.drop(l,axis=1)

var3
b     2
c     2
d     2
e     5

gözlem ve değişken seçimi

In [139]:
m=np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0    20     4     6
1    29     1     6
2    29    12    26
3    25    14    14
4     5    12    18
5    26    29    12
6    12     6    19
7    25    17    18
8    22     1    10
9    10     8     4

loc
-tanımlandığı şekliyle seçim yapmak için kullanılır.

In [140]:
df.loc[0:3]

var1  var2  var3
0    20     4     6
1    29     1     6
2    29    12    26
3    25    14    14

iloc
-alışık olduğumuz indexleme mantığıyla seçim yapmak için kullanılır.

In [141]:
df.loc[0:3]

var1  var2  var3
0    20     4     6
1    29     1     6
2    29    12    26
3    25    14    14

In [147]:
df.iloc[0,0]

np.int64(20)

In [149]:
df.iloc[0:0]

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

SORU 2

In [14]:
logo_renk=input("renk giriniz:")
print("YetGen Jump Python Rengi ", logo_renk)

YetGen Jump Python Rengi  mor


### Soru 3
Dairenin alanını hesaplayan bir Python kodu yazınız. pi sayısını 3.14 olarak alınız ve yarıçapını kullanıcıdan alınız. Sonucu ekrana bastırınız.

In [37]:
pi=3.14
r=5
alan=print(pi*r*r)

78.5


### Soru 4
x ve y adında iki liste oluşturunuz. Bu listeleri birbiryle yer değiştirerek yazdırınız.

```python
x = [1,2,3,4,5]
y = [5,4,3,2,1]
``` 

```python	
Output:
x = [5, 4, 3, 2, 1]
y = [1, 2, 3, 4, 5]
```

In [38]:
x=1,3,5,7
y=2,4,6,8
print("x=", y)
print("y=", x)

x= (2, 4, 6, 8)
y= (1, 3, 5, 7)


### Soru 5
Aşağıda verilen kod satırının sonuncunu 1 olacak şekilde düzenleyiniz.

In [39]:
5 - 3 // 2
a=5
b=3
c=2


In [40]:
print((a-b)/c)

1.0


### Soru 6
Aşağıdaki kod satırının sonuncusunu 0 olacak şekilde düzenleyiniz.

In [ ]:
8 - (3 * 2) - (1 + 1)

0

### Soru 7
YetGen liderlerinden Berkcan, Emirhan ve Eslem, Ramazan Bayramı'nda topladıkları şekerlerini bir araya getirmeyi ve kendi aralarında eşit olarak paylaşmayı kabul ettiler.
Eşit paylaşım yapıldıktan sonra kalan şekerler parçalanacak. Örneğin, eğer toplamda 91 şekerleri varsa , her biri 30 tane alıp kalan 1 tane şekeri parçalayacaklar.
Kaç tane şekeri parçalayacaklarını hesaplayan bir Python kodu yazınız.

In [3]:
toplam_şeker=input("sayı giriniz:")
a=print(toplam_şeker)
a=int(toplam_şeker)
toplam_şeker=int(toplam_şeker)
b=print((toplam_şeker)/3)
b=int((toplam_şeker)/3)
sonuç=print(a-3*b)


56
18.666666666666668
2


2. Diyet Planı Oluşturma

Proje Adı: Diyet Planı Oluşturma

Açıklama:

	•	Kullanıcının yaş, cinsiyet, boy, kilo ve aktivite seviyesine göre kişiselleştirilmiş diyet planı oluşturun.
	•	Kullanıcının günlük kalori ihtiyacını hesaplayın ve önerilerde bulunun.

Adımlar:

	1.	Veri Toplama: Kullanıcı verilerini alın.
	2.	Veri Temizleme: Eksik veya hatalı verileri düzeltin.
	3.	Kalori Hesaplama: Kullanıcının günlük kalori ihtiyacını hesaplayın.
	4.	Diyet Planı Oluşturma: Kullanıcının ihtiyacına göre yiyecekler önerin.

Örnek Kod:

In [ ]:
def calculate_calories(age, gender, weight, height, activity_level):
    if gender == 'male':
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161
    activity_multiplier = {'sedentary': 1.2, 'light': 1.375, 'moderate': 1.55, 'active': 1.725}
    return bmr * activity_multiplier[activity_level]

def create_diet_plan(calories):
    foods = {
        'breakfast': [('oatmeal', 150), ('egg', 78), ('banana', 105)],
        'lunch': [('chicken breast', 165), ('quinoa', 120), ('broccoli', 55)],
        'dinner': [('salmon', 200), ('sweet potato', 112), ('asparagus', 40)],
        'snack': [('almonds', 160), ('apple', 95), ('yogurt', 59)]
    }
    plan = {}
    for meal, items in foods.items():
        meal_calories = sum([item[1] for item in items])
        portion = calories / (meal_calories * 4)
        plan[meal] = [(item[0], item[1] * portion) for item in items]
    return plan

# Kullanıcı bilgileri
age = 25
gender = 'female'
weight = 70  # kg
height = 170  # cm
activity_level = 'moderate'

# Kalori ihtiyacını hesapla
calories_needed = calculate_calories(age, gender, weight, height, activity_level)

# Diyet planı oluştur
diet_plan = create_diet_plan(calories_needed)
print(diet_plan)

Tabii ki! Bu diyet planı projesini daha kapsamlı ve ilgi çekici hale getirmek için birkaç ek özellik ekleyebiliriz:

	1.	Farklı Diyet Tipleri Ekleyin:
	•	Vegan, vejetaryen, düşük karbonhidrat gibi farklı diyet türlerini destekleyin.
	2.	Besin Değerlerini Hesaplayın:
	•	Kaloriye ek olarak, protein, karbonhidrat, yağ gibi besin değerlerini de hesaplayın.
	3.	Kullanıcı Geri Bildirimi ve Ayarlamalar:
	•	Kullanıcının diyet planını değerlendirmesine olanak tanıyın ve gerektiğinde planı ayarlayın.
	4.	Haftalık Plan Oluşturun:
	•	Tek günlük plan yerine haftalık planlar oluşturun.
	5.	Rastgele Yemek Önerileri:
	•	Her yemek için rastgele yemek önerileri sunun.

İşte bu ek özelliklerle daha detaylı bir proje örneği:

In [ ]:
import numpy as np

def calculate_calories(age, gender, weight, height, activity_level):
    if gender == 'male':
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161
    activity_multiplier = {'sedentary': 1.2, 'light': 1.375, 'moderate': 1.55, 'active': 1.725}
    return bmr * activity_multiplier[activity_level]

def create_diet_plan(calories, diet_type='standard'):
    foods = {
        'standard': {
            'breakfast': [('oatmeal', 150, 5, 27, 3), ('egg', 78, 6, 1, 5), ('banana', 105, 1, 27, 0)],
            'lunch': [('chicken breast', 165, 31, 0, 3), ('quinoa', 120, 4, 21, 2), ('broccoli', 55, 4, 11, 0)],
            'dinner': [('salmon', 200, 22, 0, 13), ('sweet potato', 112, 2, 26, 0), ('asparagus', 40, 2, 7, 0)],
            'snack': [('almonds', 160, 6, 6, 14), ('apple', 95, 0, 25, 0), ('yogurt', 59, 10, 3, 0)]
        },
        'vegan': {
            'breakfast': [('smoothie', 200, 5, 50, 1), ('chia pudding', 180, 6, 20, 9)],
            'lunch': [('tofu stir-fry', 250, 20, 30, 10), ('quinoa salad', 200, 6, 35, 5)],
            'dinner': [('lentil soup', 250, 18, 40, 8), ('vegan burger', 300, 22, 45, 12)],
            'snack': [('hummus & carrots', 150, 4, 20, 8), ('fruit salad', 100, 1, 25, 0)]
        }
    }
    
    chosen_foods = foods[diet_type]
    plan = {}
    for meal, items in chosen_foods.items():
        meal_calories = sum([item[1] for item in items])
        portion = calories / (meal_calories * 4)
        plan[meal] = [(item[0], item[1] * portion, item[2] * portion, item[3] * portion, item[4] * portion) for item in items]
    return plan

def summarize_diet_plan(plan):
    summary = {}
    for meal, items in plan.items():
        total_calories = sum([item[1] for item in items])
        total_protein = sum([item[2] for item in items])
        total_carbs = sum([item[3] for item in items])
        total_fat = sum([item[4] for item in items])
        summary[meal] = {
            'calories': total_calories,
            'protein': total_protein,
            'carbs': total_carbs,
            'fat': total_fat
        }
    return summary

# Kullanıcı bilgileri
age = 25
gender = 'female'
weight = 70  # kg
height = 170  # cm
activity_level = 'moderate'
diet_type = 'vegan'  # standard veya vegan seçilebilir

# Kalori ihtiyacını hesapla
calories_needed = calculate_calories(age, gender, weight, height, activity_level)

# Diyet planı oluştur
diet_plan = create_diet_plan(calories_needed, diet_type)

# Diyet planı özetini oluştur
diet_summary = summarize_diet_plan(diet_plan)

print("Diyet Planı:")
for meal, items in diet_plan.items():
    print(f"{meal.capitalize()}:")
    for item in items:
        print(f"  - {item[0]}: {item[1]:.2f} kcal, Protein: {item[2]:.2f}g, Karbonhidrat: {item[3]:.2f}g, Yağ: {item[4]:.2f}g")

print("\nDiyet Özeti:")
for meal, nutrients in diet_summary.items():
    print(f"{meal.capitalize()}: {nutrients['calories']:.2f} kcal, Protein: {nutrients['protein']:.2f}g, Karbonhidrat: {nutrients['carbs']:.2f}g, Yağ: {nutrients['fat']:.2f}g")

Yeni Eklenen Özellikler:

	1.	Farklı Diyet Tipleri: diet_type parametresiyle vegan ve standart diyetler arasında seçim yapılabilir.
	2.	Besin Değerleri: Her öğün için kalori, protein, karbonhidrat ve yağ miktarları hesaplanır.
	3.	Haftalık Plan: Tek günlük plan yerine haftalık plan oluşturma fikri eklenebilir.
	4.	Rastgele Yemek Önerileri: Yemekler rastgele seçilebilir.

Bu şekilde projenizi daha ilgi çekici ve kapsamlı hale getirebilirsiniz.

5. Basit Şifreleme ve Şifre Çözme

Proje Adı: Basit Şifreleme ve Şifre Çözme

Açıklama:

	•	Kullanıcının girdiği metni basit bir şifreleme algoritması ile şifreleyin ve çözün.

Adımlar:

	1.	Şifreleme Fonksiyonu: Basit bir şifreleme algoritması yazın.
	2.	Şifre Çözme Fonksiyonu: Şifrelenmiş metni çözen bir fonksiyon yazın.
	3.	Kullanıcı Girdisi: Kullanıcıdan metin ve şifreleme anahtarı alın.
	4.	Sonuç Gösterme: Şifrelenmiş ve çözülmüş metni ekranda gösterin.

Örnek Kod:

In [ ]:
def sifreleme(metin, anahtar):
    sifreli_metin = ""
    for karakter in metin:
        sifreli_metin += chr(ord(karakter) + anahtar)
    return sifreli_metin

def sifre_cozme(sifreli_metin, anahtar):
    cozulmus_metin = ""
    for karakter in sifreli_metin:
        cozulmus_metin += chr(ord(karakter) - anahtar)
    return cozulmus_metin

metin = input("Şifrelenecek metni girin: ")
anahtar = int(input("Şifreleme anahtarını girin (sayı): "))

sifreli_metin = sifreleme(metin, anahtar)
print(f"Şifreli Metin: {sifreli_metin}")

cozulmus_metin = sifre_cozme(sifreli_metin, anahtar)
print(f"Çözülmüş Metin: {cozulmus_metin}")

1. Film Öneri Sistemi

Proje Adı: Film Öneri Sistemi

Açıklama:

	•	Kullanıcıların izlediği filmlere ve verdikleri oylara göre yeni filmler önerin.
	•	Kullanıcıların tercihlerini öğrenerek kişiselleştirilmiş öneriler yapın.

Adımlar:

	1.	Veri Toplama: Film puanları ve kullanıcı verilerini içeren bir veri seti kullanın.
	2.	Veri Temizleme: Eksik veya hatalı verileri düzeltin.
	3.	Özellik Mühendisliği: Kullanıcı-film matrisi oluşturun.
	4.	Model Eğitim: Basit bir kullanıcı tabanlı işbirlikçi filtreleme algoritması kullanın.
	5.	Öneri Yapma: Kullanıcıların beğenebileceği filmleri önerin.

Örnek Kod:

In [ ]:
import csv
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Veriyi yükle
def load_data(file_name):
    with open(file_name, newline='', encoding='utf-8') as file:
        reader = csv.reader(file)
        data = list(reader)
    return data

ratings = load_data('ratings.csv')

# Kullanıcı-film matrisi oluştur
user_ids = list(set([int(row[0]) for row in ratings[1:]]))
movie_ids = list(set([int(row[1]) for row in ratings[1:]]))

user_movie_matrix = np.zeros((len(user_ids), len(movie_ids)))

for row in ratings[1:]:
    user_id = int(row[0])
    movie_id = int(row[1])
    rating = float(row[2])
    user_movie_matrix[user_ids.index(user_id)][movie_ids.index(movie_id)] = rating

# Benzerlik matrisini hesapla
user_similarity = cosine_similarity(user_movie_matrix)
user_similarity[user_similarity < 0] = 0  # Negatif benzerlikleri sıfıra ayarla

# Kullanıcı için film önerisi yap
def recommend_movies(user_id, num_recommendations):
    user_index = user_ids.index(user_id)
    similar_users = np.argsort(user_similarity[user_index])[::-1]
    recommended_movies = {}
    
    for similar_user in similar_users:
        if similar_user == user_index:
            continue
        for movie_index, rating in enumerate(user_movie_matrix[similar_user]):
            if user_movie_matrix[user_index][movie_index] == 0 and rating > 0:
                if movie_index not in recommended_movies:
                    recommended_movies[movie_index] = rating
                else:
                    recommended_movies[movie_index] += rating
        if len(recommended_movies) >= num_recommendations:
            break
    
    recommended_movie_indices = sorted(recommended_movies, key=recommended_movies.get, reverse=True)
    return [movie_ids[index] for index in recommended_movie_indices[:num_recommendations]]

# Önerileri yazdır
print(recommend_movies(user_id=1, num_recommendations=5))

 Proje Adı: Film Öneri Sistemi

Açıklama:

	•	Kullanıcıların izlediği filmlere ve verdikleri oylara göre yeni filmler önerin.
	•	Kullanıcıların tercihlerini öğrenerek kişiselleştirilmiş öneriler yapın.

Adımlar:

	1.	Veri Toplama: Film puanları ve kullanıcı verilerini içeren bir veri seti kullanın.
	2.	Veri Temizleme: Eksik veya hatalı verileri düzeltin.
	3.	Özellik Mühendisliği: Kullanıcı-film matrisi oluşturun.
	4.	Model Eğitim: Basit bir kullanıcı tabanlı işbirlikçi filtreleme algoritması kullanın.
	5.	Öneri Yapma: Kullanıcıların beğenebileceği filmleri önerin.

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Veriyi yükle
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

# Kullanıcı-film matrisi oluştur
user_movie_matrix = ratings.pivot(index='userId', columns='movieId', values='rating')

# Benzerlik matrisini hesapla
user_similarity = cosine_similarity(user_movie_matrix.fillna(0))
user_similarity_df = pd.DataFrame(user_similarity, index=user_movie_matrix.index, columns=user_movie_matrix.index)

# Kullanıcı için film önerisi yap
def recommend_movies(user_id, num_recommendations):
    similar_users = user_similarity_df[user_id].sort_values(ascending=False).index[1:]
    recommended_movies = pd.Series()
    for similar_user in similar_users:
        movies_watched = user_movie_matrix.loc[similar_user].dropna().index
        recommended_movies = recommended_movies.append(movies_watched)
        if len(recommended_movies) >= num_recommendations:
            break
    return recommended_movies.value_counts().index[:num_recommendations]

# Önerileri yazdır
print(recommend_movies(user_id=1, num_recommendations=5))