# Problem 1

In [9]:
import numpy as np
a=np.arange(0,10,2)
print(a.ndim)

print(a.reshape(5,1))

print(a.shape)


1
[[0]
 [2]
 [4]
 [6]
 [8]]
(5,)


# Problem 2

In [65]:
import numpy as np
a=np.arange(1,10,2)
print(a)

x,y,z=np.split(a,[1,3])
print(x,y,z)

b=np.concatenate([x,y,z])
print(b)

[1 3 5 7 9]
[1] [3 5] [7 9]
[1 3 5 7 9]


# Problem 3

In [69]:
import numpy as np
a=np.random.randint(5,100,size=10)
print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[70 45 15 84 80 14 61 37 51 59]
1
(10,)
10
int64
